'''
countries = ['FR','US','DE','RU']
print(countries)
print(countries[1])
countries[1]='GB'
print(countries)
countries.append('PL')
print(countries)
countries.insert(2,'ES')
print(countries)
countries.remove('RU')
print(countries)
countries.sort()
print(countries)
countries.reverse()
print(countries)
print(countries.pop(2))
print(countries)
print(countries.index('PL'))
print(countries.count('DE'))
newList=['FI','SE']
print(newList)
countries.extend(newList)
print(countries)
countriesCopy = countries.copy()
print(countries)
print(countriesCopy)
countriesCopy.clear()
print(countries)
print(countriesCopy)
'''
hitsTitles = ['BROTHERS IN ARMS','BOHEMIAN RHAPSODY','STAIRWAY TO HEAVEN','RIDERS ON THE STORM','WISH YOU WERE HERE']
print(hitsTitles)
hitsTitles.append('CHILD IN TIME')
hitsTitles.append('AGAIN')
print(hitsTitles)
hitsTitles.insert(2,'HOTEL CALIFORNIA')
print(hitsTitles)
hitsTitles.insert(0,'THE SOUND OF SILENCE')
print(hitsTitles)
print(hitsTitles.index('HOTEL CALIFORNIA'))
hitsTitles.remove('HOTEL CALIFORNIA')
print(hitsTitles)
hitsTitles[0]
print(hitsTitles)
hitsToRead = hitsTitles.copy()
print(hitsToRead)
hitsToRead.reverse()
print(hitsToRead)
hitsToRead.sort()
print(hitsToRead)
print(hitsToRead.pop(0))
print(hitsToRead.pop(0))
print(hitsToRead)
additionalSongs = ['NOTHING COMPARES 2 U', 'WISH YOU WERE HERE']
hitsToRead.extend(additionalSongs)
print(hitsToRead)
print(hitsToRead.count('WISH YOU WERE HERE'))
print(hitsToRead.count('RIDERS ON THE STORM'))
hitsToRead.clear()
print(hitsToRead)

