lista = [
    'Administrator baz danych',
'Administrator bezpieczeństwa informacji',
'Administrator nieruchomości',
'Administrator produkcji filmowej',
'Administrator stron internetowych',
'Administrator systemów komputerowych',
'Administrator systemów poczty elektronicznej',
'Administrator zintegrowanych systemów zarządzania',
'Adwokat',
'Agent celny',
'Agent do spraw pozyskiwania gruntów',
'Agent do spraw zakupów',
'Agent klarujący',
'Agent ubezpieczeniowy',
'Agrochemik',
'Akredytowany asystent parlamentarny',
'Akrobata',
'Aktor',
'Aktor cyrkowyS',
'Aktor lalkarz',
'Aktor scen muzycznychS',
'Aktuariusz',
'Akupunkturzysta',
'Akwizytor',
'Alpinista przemysłowy',
'Analityk baz danych',
'Analityk biznesowy',
'Analityk finansowy',
'Analityk giełdowy',
'Analityk informacji i raportów medialnych',
'Analityk inwestycyjny',
'Analityk kredytowy',
'Analityk pracy',
'Analityk ruchu na stronach internetowych',
'Analityk sieci komputerowych',
'Analityk systemów teleinformatycznych',
'Analityk trendów rynkowych (cool hunter)',
'Andragog',
'Animator czasu wolnego młodzieży (pracownik młodzieżowy)',
'Animator gospodarczy do spraw przedsiębiorczości',
'Animator gospodarczy do spraw rozwoju regionalnego',
'Animator kulturyS',
'Ankieter',
'Antropolog',
'Antykwariusz',
'Aparatowy procesów chemicznych',
'Aparatowy produkcji drożdży',
'Aparatowy produkcji octu',
'Aparatowy produkcji wyrobów maczanych',
'Archeolog',
'Architekt',
'Architekt krajobrazu',
'Architekt stron internetowych',
'Architekt wnętrz',
'Architekt zieleni wewnątrz budynków',
'Archiwista',
'Archiwista dokumentów elektronicznych',
'Archiwista zakładowy',
'Arkadownik',
'Arteterapeuta',
'Artysta fotografik',
'Artysta grafik',
'Artysta malarz',
'Artysta rzeźbiarz',
'Astrofizyk',
'Astrolog',
'Astronom',
'Asystent do spraw księgowości',
'Asystent do spraw statystyki',
'Asystent do spraw wydawniczych',
'Asystent dyrektora',
'Asystent edukacji romskiej',
'Asystent kierownika produkcji filmowej / telewizyjnejS',
'Asystent nauczyciela dziecka cudzoziemca',
'Asystent nauczyciela przedszkola',
'Asystent nauczyciela w szkole',
'Asystent operatora dźwięku',
'Asystent operatora obrazu',
'Asystent osobisty (concierge)',
'Asystent osoby niepełnosprawnejS',
'Asystent parlamentarny',
'Asystent prawny',
'Asystent prokuratora',
'Asystent przetwarzania danych',
'Asystent reżysera filmowego',
'Asystent rodziny',
'Asystent sędziego',
'Asystent techniczny realizatora dźwięku',
'Asystent techniczny realizatora programu',
'Asystent usług pocztowych',
'Asystent usług telekomunikacyjnych',
'Asystent zarządu',
'Asystentka kobiety w czasie ciąży i porodu (doula)',
'Asystentka stomatologicznaS',
'Audiofonolog',
'Audytor',
'Audytor środowiskowy',
'Audytor energetyczny',
'Automatyk sterowania ruchem kolejowym',
'Autor tekstów i sloganów reklamowych (copywriter)',
'Baca',
'Bagażowy',
'Bandażysta ortopedyczny',
'Barista',
'Barman',
'Bednarz',
'Betoniarz',
'Betoniarz-zbrojarzS',
'BibliotekarzS',
'Bibliotekoznawca',
'Biegły rewident',
'Bieliźniarz',
'Bieliźniarz-kołdrzarz',
'Bileter',
'Biochemik',
'Bioenergoterapeuta',
'Biofizyk',
'Bioinformatyk',
'Bioinżynier',
'Biolog',
'Biomasażysta',
'Biotechnolog',
'Blacharz budowlany',
'Blacharz izolacji przemysłowychS',
'Blacharz lotniczy',
'Blacharz okrętowy',
'BlacharzS',
'Blacharz samochodowyS',
'Blogier / vloger',
'Bosman portu',
'Bosman żeglugi śródlądowej',
'Boy hotelowy',
'Brązownik',
'Broker edukacyjny',
'Broker informacji (researcher)',
'Broker reasekuracyjny',
'Broker ubezpieczeniowy',
'Brukarz',
'Bukieciarz',
'Bukmacher',
'Bursztyniarz',
'Cechowacz skal i znaków na szkle oraz na wyrobach z metali',
'Cechowniczy',
'Ceramik wyrobów ceramiki budowlanej',
'Ceramik wyrobów użytkowych i ozdobnych',
'Charakteryzator',
'Chemik',
'Chemik – technologia chemiczna',
'Chiropraktyk',
'Chirurg pielęgniarz drzew',
'Cholewkarz',
'Choreograf',
'Ciągacz rur',
'CieślaS',
'Cieśla szalunkowy',
'CukiernikS',
'Cykliniarz',
'Czyściciel basenów pływackich',
'Czyściciel butów',
'Czyściciel dywanów',
'Czyściciel elewacji budowlanych',
'Czyściciel pojazdów',
'Dealer aktywów finansowych',
'DekarzS',
'Dekorator sklepów',
'Dekorator wnętrz',
'Dekorator wyrobów cukierniczych',
'Demograf',
'Demonstrator wyrobów',
'Detektyw prywatny',
'Diagnosta kolejowy',
'Diagnosta laboratoryjny',
'Diagnosta laboratoryjny – specjalista cytomorfologii medycznej',
'Diagnosta laboratoryjny – specjalista epidemiologii',
'Diagnosta laboratoryjny – specjalista laboratoryjnej diagnostyki medycznej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej genetyki sądowej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej genetyki medycznej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej hematologii medycznej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej immunologii medycznej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej parazytologii medycznej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej toksykologii medycznej',
'Diagnosta laboratoryjny – specjalista laboratoryjnej transfuzjologii medycznej',
'Diagnosta laboratoryjny – specjalista mikrobiologii medycznej',
'Diagnosta laboratoryjny – specjalista zdrowia publicznego',
'Diagnosta laboratoryjny – specjalista zdrowia środowiskowego',
'Diagnosta laboratoryjny – specjalista laboratoryjnej toksykologii sądowej',
'Diagnosta uprawniony do wykonywania badań technicznych pojazdów',
'Dietetyk',
'Docieracz-polerowacz',
'Dojarz',
'Doradca do spraw bezpieczeństwa przewozu koleją towarów niebezpiecznych (Doradca RID)',
'Doradca do spraw bezpieczeństwa w transporcie towarów niebezpiecznych',
'Doradca do spraw leasingu',
'Doradca do spraw odszkodowań',
'Doradca do spraw rynku nieruchomości',
'Doradca do spraw zasobów bibliotecznych',
'Doradca emerytalny',
'Doradca EURES',
'Doradca finansowy',
'Doradca inwestycyjny',
'Doradca klienta',
'Doradca personalny',
'Doradca podatkowy',
'Doradca rolniczy',
'Doradca zawodowy',
'Dorożkarz',
'Dostawca potraw',
'Dozorca',
'Dróżnik obchodowy',
'Dróżnik przejazdowy',
'DrukarzS',
'Drukarz sitodrukowy',
'Drukarz tkanin',
'Drwal / pilarz drzew',
'Duchowny religii mojżeszowej',
'Duchowny religii muzułmańskiej',
'Duchowny wyznania ewangelickiego',
'Duchowny wyznania prawosławnego',
'Duchowny wyznania rzymskokatolickiego',
'Dydaktyk multimedialny',
'Dyrektor aresztu śledczego / zakładu karnego',
'Dyrektor departamentu',
'Dyrektor do spraw administracyjnych',
'Dyrektor do spraw badawczo-rozwojowych',
'Dyrektor do spraw energetyki',
'Dyrektor do spraw informatyki / informacji',
'Dyrektor do spraw personalnych',
'Dyrektor do spraw wdrożeń i rozwoju technologii',
'Dyrektor finansowy',
'Dyrektor generalny',
'Dyrektor handlowy',
'Dyrektor logistyki',
'Dyrektor marketingu',
'Dyrektor operacyjny',
'Dzienny opiekun małego dziecka',
'Dyrektor ośrodka adopcyjnego',
'Dyrektor placówki opiekuńczo - wychowawczej',
'Dyrektor produkcji',
'Dyrektor rozwoju biznesu',
'Dyrektor sprzedaży',
'Dyrektor szkoły',
'Dyrektor techniczny',
'Dyrektor wykonawczy',
'Dyrektor zakładu dla nieletnich',
'Dyrygent',
'Dyspozytor lotniczy',
'Dyspozytor radio taxi',
'Dyspozytor ruchu metra',
'Dyspozytor transportu samochodowego',
'Dystrybutor ulotek',
'Dyżurny ruchu',
'Dyspozytor ruchu kolejowego',
'Dyżurny ruchu i stacji metra',
'Dziekan',
'Dziennikarz',
'Dziewiarz',
'Dźwigowy (windziarz)',
'Dżokej',
'Edukator ekologiczny',
'Edytor materiałów źródłowych',
'Eguterzysta',
'Egzaminator on-line',
'Egzaminator osób ubiegających się o uprawnienia do kierowania pojazdem',
'Elektryk budowlany',
'Ekolog',
'Ekonometryk',
'Ekonomista',
'Ekspedient pocztowy',
'Ekspedient w punkcie usługowym',
'Ekspedient w stacji obsługi pojazdów',
'Ekspedient wypożyczalni',
'Ekspedytor',
'Ekspedytor sprzedaży wysyłkowej / internetowej',
'Ekspert w Urzędzie Patentowym RP',
'Eksploatator portu',
'Ekspozytor towarów (merchandiser)',
'Elektroenergetyk elektrowni cieplnych',
'Elektroenergetyk elektrowni wodnych',
'Elektroenergetyk nastawni',
'Elektroenergetyk pomiarów i zabezpieczeń',
'Elektromechanik elektrycznych przyrządów pomiarowych',
'Elektromechanik pojazdów samochodowychS',
'ElektromechanikS',
'Elektromechanik sprzętu gospodarstwa domowego',
'Elektromechanik urządzeń chłodniczych',
'Elektromechanik urządzeń sterowania ruchem kolejowym',
'Elektromonter (elektryk) zakładowy',
'Elektromonter / konserwator urządzeń dźwignicowych',
'Elektromonter instalacji elektrycznych',
'Elektromonter linii kablowych',
'Elektromonter linii napowietrznych niskich i średnich napięć',
'Elektromonter linii napowietrznych wysokich i najwyższych napięć',
'Elektromonter lotniczy',
'Elektromonter maszyn elektrycznych',
'Elektromonter maszyn i urządzeń górnictwa odkrywkowego',
'Elektromonter maszyn i urządzeń górnictwa podziemnego',
'Elektromonter okrętowy',
'Elektromonter pogotowia elektroenergetycznego',
'Elektromonter prefabrykowanych stacji transformatorowych',
'Elektromonter reklam świetlnych',
'Elektromonter rozdzielni i podstacji trakcyjnych',
'Elektromonter sieci trakcyjnej',
'Elektromonter taboru szynowego',
'Elektromonter telekomunikacyjnych urządzeń zasilających',
'Elektromonter transformatorów',
'Elektromonter układów pomiarowych i automatyki zabezpieczeniowej',
'Elektromonter urządzeń sygnalizacyjnych',
'Elektroradiolog',
'ElektrykS',
'Epidemiolog',
'Etnograf',
'Ewaluator programów edukacji',
'Fajkarz',
'Fakturzystka',
'Farmaceuta',
'Farmaceuta – specjalista analityki farmaceutycznej',
'Farmaceuta – specjalista bromatologii',
'Farmaceuta – specjalista farmacji aptecznej',
'Farmaceuta – specjalista farmacji klinicznej',
'Farmaceuta – specjalista farmacji przemysłowej',
'Farmaceuta – specjalista farmacji szpitalnej',
'Farmaceuta – specjalista farmakologii',
'Farmaceuta – specjalista leku roślinnego',
'Farmaceuta – specjalista mikrobiologia i biotechnologia farmaceutyczna',
'Farmaceuta – specjalista toksykologii',
'Farmaceuta – specjalista zdrowia publicznego',
'Farmaceuta – specjalista zdrowia środowiskowego',
'Felczer',
'Filolog języka nowożytnego',
'Filolog klasyczny',
'Filolog polski',
'Filozof',
'Fizjoterapeuta',
'Fizyk',
'Fizyk medyczny',
'Flisak - retman',
'FlorystaS',
'Formierz odlewnik',
'Formierz wyrobów z kompozytów polimerowych',
'Formowacz ortopedycznych wyrobów z tworzyw',
'Formowacz ściernic',
'Formowacz wyrobów ceramicznych',
'Formowacz wyrobów szklanych',
'Fotoedytor',
'Fotograf poligraficzny',
'FotografS',
'Fotograf w drukarni filmowej',
'Fotoreporter',
'Fotosista',
'FototechnikS',
'Frezer',
'Frezer drewna',
'Fryzjer damski',
'Fryzjer męski',
'FryzjerS',
'Fryzjer zwierząt (groomer)',
'Funkcjonariusz Biura Ochrony Rządu',
'Funkcjonariusz celny',
'Funkcjonariusz służb specjalnych',
'Funkcjonariusz służby ochrony',
'Funkcjonariusz służby penitencjarnej',
'Funkcjonariusz straży granicznej',
'Funkcjonariusz staży ochrony kolei',
'Galwanizer',
'Garbarz skór bez włosa',
'Garbarz skórS',
'Garderobiana',
'Garmażer',
'Garncarz',
'Gemmolog',
'Genetyk',
'Geofizyk',
'Geograf',
'Geolog',
'Gięciarz drewna',
'Giloszer poligraficzny',
'Giloszer szkła',
'Glazurnik',
'Gleboznawca',
'Główny księgowy',
'Główny technolog',
'Goniec',
'Gorseciarka',
'Gospodarz domu',
'Gospodyni',
'Górnik eksploatacji otworowejS',
'Górnik eksploatacji podziemnejS',
'Górnik odkrywkowej eksploatacji złóżS',
'Grabarz',
'Grafik komputerowy DTP',
'Grafik komputerowy multimediów',
'Grawer',
'Grawer poligraficzny',
'Grawer szkła',
'Grzyboznawca',
'Hafciarka',
'Hartowacz betonów i sylikatów',
'Hartownik',
'Higienistka stomatologicznaS',
'Higienistka szkolna',
'Historyk',
'Historyk sztuki',
'Hodowca bydła',
'Hodowca drobiu',
'Hodowca inwentarza mieszanego',
'Hodowca jedwabników',
'Hodowca koni',
'Hodowca owiec',
'Hodowca ptaków',
'Hodowca ryb',
'Hodowca trzody chlewnej',
'Hodowca zwierząt domowych',
'Hodowca zwierząt futerkowych',
'Hodowca zwierząt laboratoryjnych',
'Hodowca zwierząt pracujący na własne potrzeby',
'Homeopata',
'Hostessa',
'Hutnik dmuchacz szkła',
'Hydraulik',
'Hydrograf morski',
'Hydrolog',
'Hydrometeorolog',
'Ilustrator',
'Iluzjonista',
'Imitator efektów dźwiękowych',
'Impregnator drewna',
'Informator ruchu pasażerskiego',
'Informator służby informacji powietrznej',
'Informator lotniskowej służby informacji powietrznej',
'Informatyk medyczny',
'Inkasent',
'Inspektor bezpieczeństwa i higieny pracy',
'Inspektor bezpieczeństwa żeglugi',
'Inspektor budowlany',
'Inspektor budowy dróg',
'Inspektor budowy mostów',
'Inspektor do spraw miar i wag',
'Inspektor do spraw wytwarzania Głównego Inspektoratu Farmaceutycznego',
'Inspektor dozoru jądrowego',
'Inspektor dozoru technicznego',
'Inspektor farmaceutyczny',
'Inspektor hotelowy',
'Inspektor kontroli handlu i usług',
'Inspektor kontroli skarbowej',
'Inspektor nadzoru bankowego',
'Inspektor nadzoru budowlanego',
'Inspektor obrony cywilnej',
'Inspektor ochrony danych osobowych',
'Inspektor ochrony przeciwpożarowej',
'Inspektor ochrony radiologicznej',
'Inspektor rybołówstwa morskiego',
'Inspektor ochrony środowiska',
'Inspektor pracy',
'Inspektor sanitarny',
'Inspektor Inspekcji Transportu Drogowego',
'Inspicjent',
'Instalator systemów alarmowych',
'Instalator systemów alarmowych przeciwkradzieżowych',
'Instalator systemów telewizji przemysłowej',
'Instruktor amatorskiego ruchu artystycznego',
'Instruktor fitness',
'Instruktor gimnastyki korekcyjnej',
'Instruktor higieny',
'Instruktor hipoterapii',
'Instruktor jazdy konnej',
'Instruktor nauki jazdy',
'Instruktor odnowy biologicznej',
'Instruktor rekreacji ruchowej',
'Instruktor rytmiki',
'Instruktor sportów ekstremalnych',
'Instruktor sportów siłowych',
'Instruktor sportu',
'Instruktor sportu osób niepełnosprawnych',
'Instruktor strzałowy',
'Instruktor sztuki walki',
'Instruktor tańca',
'Instruktor techniki jazdy',
'Instruktor terapii uzależnień',
'Instrumentalista',
'Intendent',
'Introligator galanteryjny',
'Introligator poligraficzny',
'IntroligatorS',
'Inwentaryzator',
'Inżynier akustyk',
'Inżynier automatyki i robotyki',
'Inżynier awionik',
'Inżynier biocybernetyki i inżynierii biomedycznej',
'Inżynier budownictwa – budowle i drogi wodne',
'Inżynier budownictwa – budownictwo ogólne',
'Inżynier budownictwa – budownictwo przemysłowe',
'Inżynier budownictwa – linie, węzły i stacje kolejowe',
'Inżynier budownictwa – urządzenia, instalacje i sieci energetyczne',
'Inżynier budownictwa – wyburzanie obiektów',
'Inżynier budownictwa okrętowego',
'Inżynier budowy dróg',
'Inżynier budowy mostów',
'Inżynier elektroenergetyk',
'Inżynier elektroenergetyk kolejowych sieci i podstacji trakcyjnych',
'Inżynier elektronik',
'Inżynier elektryk',
'Inżynier elektryk automatyk',
'Inżynier energetyk',
'Inżynier geodeta – fotogrametria i teledetekcja',
'Inżynier geodeta – geodezja górnicza',
'Inżynier geodeta – geodezja inżynieryjno-przemysłowa',
'Inżynier geodeta – geodezja urządzania terenów rolnych i leśnych',
'Inżynier geodeta – geodezyjne pomiary podstawowe i satelitarne',
'Inżynier geodeta – geomatyka',
'Inżynier geodeta – kataster i gospodarka nieruchomościami',
'Inżynier geofizyk – geofizyka górnicza',
'Inżynier geolog – geologia górnicza i poszukiwawcza',
'Inżynier geolog – hydrologia górnicza',
'Inżynier geotechnik',
'Inżynier gospodarki przestrzennej',
'Inżynier górnik – górnictwo otworowe',
'Inżynier górnik – górnictwo odkrywkowe',
'Inżynier górnik – górnictwo podziemne',
'Inżynier górnik – wiertnictwo',
'Inżynier hutnik',
'Inżynier inżynierii chemicznej',
'Inżynier inżynierii materiałowej',
'Inżynier inżynierii środowiska – gazowe urządzenia, instalacje i sieci energetyczne',
'Inżynier inżynierii środowiska – gospodarka wodna i hydrologia',
'Inżynier inżynierii środowiska – instalacje sanitarne',
'Inżynier inżynierii środowiska – melioracje',
'Inżynier inżynierii środowiska – oczyszczanie miast i gospodarka odpadami',
'Inżynier inżynierii środowiska – systemy wodociągowe i kanalizacyjne',
'Inżynier kliniczny',
'Inżynier leśnictwa',
'Inżynier mechanik – cieplno-mechaniczne urządzenia, instalacje i sieci energetyczne',
'Inżynier mechanik – maszyny i urządzenia do obróbki metali',
'Inżynier mechanik – maszyny i urządzenia energetyczne',
'Inżynier mechanik – maszyny i urządzenia przemysłowe',
'Inżynier mechanik – mechanika precyzyjna',
'Inżynier mechanik – środki transportu',
'Inżynier mechanik – technologia mechaniczna',
'Inżynier mechanik lotniczy',
'Inżynier mechanizacji rolnictwa',
'Inżynier mechatronik',
'Inżynier normowania pracy',
'Inżynier odlewnik',
'Inżynier ogrodnictwa',
'Inżynier organizacji i planowania produkcji',
'Inżynier poligrafii',
'Inżynier pożarnictwa',
'Inżynier procesu malowania',
'Inżynier rolnictwa',
'Inżynier ruchu drogowego',
'Inżynier ruchu kolejowego',
'Inżynier rybactwa',
'Inżynier spawalnik',
'Inżynier sprzedaży',
'Inżynier sprzedaży technologii i usług teleinformatycznych',
'Inżynier systemów bezpieczeństwa jądrowego i ochrony radiologicznej',
'Inżynier systemów i sieci komputerowych',
'Inżynier systemów zabezpieczeń technicznych osób i mienia',
'Inżynier techniki świetlnej',
'Inżynier technologii betonów',
'Inżynier technologii ceramiki',
'Inżynier technologii chemicznej',
'Inżynier technologii drewna',
'Inżynier technologii przetwórstwa skóry',
'Inżynier technologii szkła',
'Inżynier technologii żywności',
'Inżynier teleinformatyk',
'Inżynier telekomunikacji',
'Inżynier transportu drogowego',
'Inżynier transportu kolejowego',
'Inżynier urządzeń i systemów energetyki odnawialnej',
'Inżynier urządzeń zabezpieczenia i sterowania ruchem kolejowym',
'Inżynier utrzymania ruchu',
'Inżynier włókiennik',
'Inżynier zaopatrzenia, transportu i magazynowania',
'Inżynier zootechniki',
'Jeliciarz',
'Juhas',
'KaletnikS',
'KamieniarzS',
'Kapelusznik-czapnik',
'Kapitan portu morskiego',
'Kapitan statku morskiego',
'Kapitan żeglugi przybrzeżnej',
'Kapitan żeglugi śródlądowej',
'Karmelarz',
'Kartograf',
'Kasjer bankowy',
'Kasjer biletowy',
'Kasjer handlowy',
'Kasjer w zakładzie pracy',
'Kasjer walutowy',
'Kaskader filmowy',
'Kaskader filmowy – koordynator',
'KelnerS',
'Kierowca autobusu',
'Kierowca autocysterny',
'Kierowca ciągnika rolniczego',
'Kierowca ciągnika siodłowego',
'Kierowca drezyny i wózka motorowego',
'Kierowca lokomotywy spalinowej',
'Kierowca mechanik',
'Kierowca operator wózków jezdniowych (widłowych)',
'Kierowca samochodu ciężarowego',
'Kierowca samochodu dostawczego',
'Kierowca samochodu osobowego',
'Kierowca trolejbusu',
'Kierownik agencji do spraw usług sportowych / turystycznych / kulturalnych',
'Kierownik agencji doradztwa finansowego',
'Kierownik agencji filmowej / telewizyjnej',
'Kierownik agencji ochrony mienia i osób',
'Kierownik agencji reklamowej',
'Kierownik agencji ubezpieczeniowej',
'Kierownik apteki',
'Kierownik archiwum',
'Kierownik biblioteki',
'Kierownik biura',
'Kierownik biura podroży',
'Kierownik biura rachunkowego',
'Kierownik biura tłumaczeń',
'Kierownik budowy',
'Kierownik centrum handlowego',
'Kierownik centrum konferencyjnego',
'Kierownik centrum obsługi telefonicznej (kierownik call center)',
'Kierownik centrum rozrywki dla dzieci',
'Kierownik do spraw kateringu',
'Kierownik do spraw kontroli jakości',
'Kierownik do spraw marketingu',
'Kierownik do spraw marketingu internetowego',
'Kierownik do spraw marketingu sieciowego (wielopoziomowego)',
'Kierownik do spraw rozwoju produktu',
'Kierownik do spraw sprzedaży',
'Kierownik do spraw strategicznych i planowania',
'Kierownik do spraw windykacji',
'Kierownik domu kultury',
'Kierownik domu pomocy społecznej',
'Kierownik domu spokojnej starości',
'Kierownik działu administracyjno-gospodarczego',
'Kierownik działu badawczo-rozwojowego',
'Kierownik działu finansowego',
'Kierownik działu informatyki',
'Kierownik działu kadr i płac',
'Kierownik działu logistyki',
'Kierownik działu operacji finansowych',
'Kierownik działu reklamy / promocji / public relations',
'Kierownik działu szkoleń',
'Kierownik działu transportu',
'Kierownik działu w handlu detalicznym',
'Kierownik działu w handlu hurtowym',
'Kierownik działu w hotelu',
'Kierownik działu w instytucjach pomocy społecznej',
'Kierownik działu w lokalu gastronomicznym',
'Kierownik działu w przedsiębiorstwie telekomunikacyjnym',
'Kierownik działu ruchu zakładu górniczego lub zakładu',
'Kierownik działu zakupów',
'Kierownik działu zarządzania zasobami ludzkimi',
'Kierownik firmy audytorskiej',
'Kierownik firmy sprzątającej',
'Kierownik galerii sztuki',
'Kierownik gospodarstwa hodowli drobiu',
'Kierownik gospodarstwa ogrodniczego',
'Kierownik gospodarstwa produkcji roślinnej i zwierzęcej',
'Kierownik gospodarstwa produkcji zwierzęcej',
'Kierownik gospodarstwa sadowniczego',
'Kierownik gospodarstwa upraw mieszanych',
'Kierownik gospodarstwa upraw polowych',
'Kierownik hospicjum',
'Kierownik hostelu / motelu',
'Kierownik hotelu',
'Kierownik hurtowni',
'Kierownik jednostki ratownictwa górniczego',
'Kierownik kancelarii prawnej',
'Kierownik kas',
'Kierownik kasyna',
'Kierownik kempingu',
'Kierownik kina',
'Kierownik klubu fitness',
'Kierownik klubu sportowego',
'Kierownik komórki organizacyjnej podmiotu leczniczego',
'Kierownik lokalu gastronomicznego',
'Kierownik magazynu',
'Kierownik małego przedsiębiorstwa budowlanego',
'Kierownik małego przedsiębiorstwa w przemyśle przetwórczym',
'Kierownik muzeum',
'Kierownik ośrodka pomocy rodzinie',
'Kierownik parku rozrywki / cyrku',
'Kierownik pensjonatu',
'Kierownik placówki bankowej',
'Kierownik placówki wsparcia dziennego',
'Kierownik podmiotu leczniczego',
'Kierownik planu filmowego',
'Kierownik pociągu',
'Kierownik prac podwodnych',
'Kierownik produkcji filmowej / telewizyjnej / radiowej',
'Kierownik produkcji w przedsiębiorstwie hodowlanym',
'Kierownik produkcji w przedsiębiorstwie ogrodniczym',
'Kierownik produkcji w przedsiębiorstwie rolnym',
'Kierownik produkcji w przemyśle',
'Kierownik produkcji w zakładach akwakultury',
'Kierownik projektu',
'Kierownik przedsiębiorstwa informatycznego',
'Kierownik przedsiębiorstwa spedycyjnego',
'Kierownik przedsiębiorstwa świadczącego usługi osobiste i porządkowe',
'Kierownik przedsiębiorstwa świadczącego usługi z zakresu marketingu i sprzedaży',
'Kierownik przedsiębiorstwa świadczącego usługi z zakresu obsługi biznesu',
'Kierownik przedsiębiorstwa świadczącego usługi z zakresu zarządzania zasobami ludzkimi',
'Kierownik przedsiębiorstwa telekomunikacyjnego',
'Kierownik przedsiębiorstwa transportowego',
'Kierownik przedsiębiorstwa usługowego związanego z leśnictwem',
'Kierownik przedsiębiorstwa w rybołówstwie',
'Kierownik przedszkola',
'Kierownik punktu skupu',
'Kierownik rewiru / posterunku policji',
'Kierownik rozwoju technologii informatycznych',
'Kierownik rozwoju technologii telekomunikacyjnych',
'Kierownik ruchu zakładu górniczego lub zakładu',
'Kierownik sali sprzedaży',
'Kierownik sieci informatycznych',
'Kierownik siłowni',
'Kierownik sklepu / supermarketu',
'Kierownik stoiska w markecie',
'Kierownik szkoły tańca',
'Kierownik szkółki jeździeckiej',
'Kierownik teatru',
'Kierownik utrzymania ruchu',
'Kierownik w gospodarce leśnej',
'Kierownik warsztatów szkolnych',
'Kierownik / właściciel stacji paliw',
'Kierownik / właściciel szkoły jazdy',
'Kierownik / właściciel zakładu usługowego',
'Kierownik żłobka / klubu dziecięcego',
'Kierujący tramwajem (motorniczy)',
'Kinooperator',
'Kioskarz',
'Klasyfikator dziczyzny i ptactwa',
'Klasyfikator gruntów',
'Klasyfikator grzybów',
'Klasyfikator jaj, drobiu i pierza',
'Klasyfikator ryb',
'Klasyfikator skór',
'Klasyfikator wyrobów przemysłowych',
'Klaun (clown)',
'Klimatolog',
'Kodowacz (koder)',
'Kolporter',
'Kołodziej',
'Kombajnista (kierowca kombajnu)',
'Komendant policji (powiatowy, miejski, rejonowy, komisariatu)',
'Komendant powiatowy / miejski państwowej straży pożarnej',
'Komentator sportowy',
'Komendant straży gminnej / miejskiej',
'Komik',
'KominiarzS',
'Komornik sądowy',
'Kompozytor',
'Komputerowy składacz tekstu',
'Konduktor',
'Konduktor kolei linowej',
'Konfekcjoner wyrobów gumowych',
'Konferansjer',
'Konserwator budynków i stanu technicznego pomieszczeń',
'Konserwator części / sprzętu',
'Konserwator dzieł sztuki',
'Konserwator sieci i systemów komputerowych',
'Konserwator skór surowych',
'Konserwator zabytków architektury',
'Konstruktor form wtryskowych',
'Konstruktor odzieży',
'Konstruktor rozkładów jazdy',
'Konsultant / agent sprzedaży bezpośredniej',
'Konsultant do spraw kariery',
'Konsultant do spraw systemów teleinformatycznych',
'Konsultant komitetu technicznego',
'Kontroler biletów',
'Kontroler finansowy',
'Kontroler higieny mięsa',
'Kontroler jakości połączeń spawanych',
'Kontroler jakości produktów spożywczych',
'Kontroler jakości wyrobów przemysłowych',
'Kontroler kolejowy',
'Kontroler państwowy',
'Kontroler pocztowy',
'Kontroler (sterowniczy) procesów przeróbki ropy naftowej i gazu',
'Kontroler (sterowniczy) procesów w produkcji nawozów sztucznych',
'Kontroler (sterowniczy) reaktorów chemicznych',
'Kontroler (sterowniczy) robotów przemysłowych',
'Kontroler rozliczeń pieniężnych',
'Kontroler rozliczeń podatkowych',
'Kontroler ruchu lotniczego',
'Kontroler stanu technicznego pojazdów',
'Kontroler (sterowniczy) urządzeń destylacyjnych i rektyfikacyjnych',
'Kontroler (sterowniczy) urządzeń do ciągnienia i tłoczenia metali',
'Kontroler (sterowniczy) urządzeń do obróbki cieplnej chemikaliów',
'Kontroler (sterowniczy) urządzeń do produkcji papieru',
'Kontroler (sterowniczy) urządzeń do wytopu metali',
'Kontroler (sterowniczy) urządzeń filtrujących i oddzielających',
'Kontroler (sterowniczy) urządzeń koksowniczych',
'Kontroler (sterowniczy) urządzeń obróbki cieplnej metali',
'Kontroler (sterowniczy) urządzeń odlewniczych',
'Kontroler (sterowniczy) urządzeń walcowniczych',
'Konwojent (konduktor) wagonów specjalnych',
'Koordynator badań klinicznych',
'Koordynator pobierania i przeszczepiania tkanek i narządów',
'Koordynator projektów unijnych',
'Koordynator rodzinnej pieczy zastępczej',
'Kopacz',
'Korektor (naprawiacz) instrumentów muzycznych',
'Korektor i stroiciel instrumentów muzycznych',
'Korektor tekstu',
'Korepetytor',
'Koronkarka',
'Kosmetolog',
'Kosmetyczka',
'Kostiumograf',
'Kosztorysant budowlany',
'Koszykarz-plecionkarzS',
'Kościelny',
'KowalS',
'Kowal wyrobów zdobniczych',
'Kożusznik',
'Krajacz materiałów budowlanych',
'Krajacz szkła',
'KrawiecS',
'Kremator',
'Krojczy',
'Krupier',
'Kryminolog',
'Krytyk artystyczny',
'Krytyk kulinarny',
'Księgowy',
'KucharzS',
'Kulturoznawca',
'Kurator sądowy',
'Kurier',
'Kurier motocyklowy',
'KuśnierzS',
'Kynoterapeuta (dogoterapeuta)',
'Laborant mikrobiologiczny',
'Laborant biochemiczny',
'Laborant budowlany',
'Laborant chemiczny',
'Laborant nasiennictwa',
'Laborant w hodowli roślin',
'Laborant weterynaryjny',
'Lagowacz',
'Lakiernik proszkowy',
'LakiernikS',
'Lakiernik samochodowy',
'Lakiernik tworzyw sztucznych',
'Lakiernik wyrobów drzewnych',
'Latarnik',
'Legalizator',
'Legislator',
'Lekarz',
'Lekarz ordynator oddziału',
'Lekarz ze specjalizacją I stopnia',
'Lekarz – specjalista alergologii',
'Lekarz – specjalista anestezjologii i intensywnej terapii',
'Lekarz – specjalista angiologii',
'Lekarz – specjalista audiologii i foniatrii',
'Lekarz – specjalista balneologii i medycyny fizykalnej',
'Lekarz – specjalista chirurgii dziecięcej',
'Lekarz – specjalista chirurgii klatki piersiowej',
'Lekarz – specjalista chirurgii naczyniowej',
'Lekarz – specjalista chirurgii ogólnej',
'Lekarz – specjalista chirurgii onkologicznej',
'Lekarz – specjalista chirurgii plastycznej',
'Lekarz – specjalista chirurgii szczękowo-twarzowej',
'Lekarz – specjalista chorób płuc',
'Lekarz – specjalista chorób wewnętrznych',
'Lekarz – specjalista chorób zakaźnych',
'Lekarz – specjalista dermatologii i wenerologii',
'Lekarz – specjalista diabetologii',
'Lekarz – specjalista diagnostyki laboratoryjnej',
'Lekarz – specjalista endokrynologii',
'Lekarz – specjalista epidemiologii',
'Lekarz – specjalista farmakologii klinicznej',
'Lekarz – specjalista gastroenterologii',
'Lekarz – specjalista genetyki klinicznej',
'Lekarz – specjalista geriatrii',
'Lekarz – specjalista ginekologii onkologicznej',
'Lekarz – specjalista hematologii',
'Lekarz – specjalista hipertensjologii',
'Lekarz – specjalista immunologii klinicznej',
'Lekarz – specjalista kardiochirurgii',
'Lekarz – specjalista kardiologii',
'Lekarz – specjalista kardiologii dziecięcej',
'Lekarz – specjalista medycyny nuklearnej',
'Lekarz – specjalista medycyny paliatywnej',
'Lekarz – specjalista medycyny pracy',
'Lekarz – specjalista medycyny ratunkowej',
'Lekarz – specjalista medycyny rodzinnej',
'Lekarz – specjalista medycyny sądowej',
'Lekarz – specjalista medycyny sportowej',
'Lekarz – specjalista medycyny transportu',
'Lekarz – specjalista mikrobiologii lekarskiej',
'Lekarz – specjalista nefrologii',
'Lekarz – specjalista neonatologii',
'Lekarz – specjalista neurochirurgii',
'Lekarz – specjalista neurologii',
'Lekarz – specjalista neurologii dziecięcej',
'Lekarz – specjalista neuropatologii',
'Lekarz – specjalista okulistyki',
'Lekarz – specjalista onkologii i hematologii dziecięcej',
'Lekarz – specjalista onkologii klinicznej',
'Lekarz – specjalista ortopedii i traumatologia narządu ruchu',
'Lekarz – specjalista otorynolaryngologii',
'Lekarz – specjalista otorynolaryngologii dziecięcej',
'Lekarz – specjalista patomorfologii',
'Lekarz – specjalista pediatrii',
'Lekarz – specjalista położnictwa i ginekologii',
'Lekarz – specjalista psychiatrii',
'Lekarz – specjalista psychiatrii dzieci i młodzieży',
'Lekarz – specjalista radiologii i diagnostyki obrazowej',
'Lekarz – specjalista radioterapii onkologicznej',
'Lekarz – specjalista rehabilitacji medycznej',
'Lekarz – specjalista reumatologii',
'Lekarz – specjalista seksuologii',
'Lekarz – specjalista toksykologii klinicznej',
'Lekarz – specjalista transfuzjologii klinicznej',
'Lekarz – specjalista transplantologii klinicznej',
'Lekarz – specjalista urologii',
'Lekarz – specjalista urologii dziecięcej',
'Lekarz – specjalista zdrowia publicznego',
'Lekarz – specjalista chorób płuc dzieci',
'Lekarz – specjalista endokrynologii ginekologicznej i rozrodczości',
'Lekarz – specjalista endokrynologii i diabetologii dziecięcej',
'Lekarz – specjalista gastroenterologii dziecięcej',
'Lekarz – specjalista intensywnej terapii',
'Lekarz – specjalista medycyny lotniczej',
'Lekarz – specjalista medycyny morskiej i tropikalnej',
'Lekarz – specjalista nefrologii dziecięcej',
'Lekarz – specjalista pediatrii metabolicznej',
'Lekarz – specjalista perinatologii',
'Lekarz dentysta',
'Lekarz dentysta ze specjalizacją I stopnia',
'Lekarz dentysta – specjalista chirurgii stomatologicznej',
'Lekarz dentysta – specjalista chirurgii szczękowo-twarzowej',
'Lekarz dentysta – specjalista epidemiologii',
'Lekarz dentysta – specjalista ortodoncji',
'Lekarz dentysta – specjalista periodontologii',
'Lekarz dentysta – specjalista protetyki stomatologicznej',
'Lekarz dentysta – specjalista stomatologii dziecięcej',
'Lekarz dentysta – specjalista stomatologii zachowawczej z endodoncji',
'Lekarz dentysta – specjalista zdrowia publicznego',
'Lekarz weterynarii',
'Lekarz weterynarii – specjalista chirurgii weterynaryjnej',
'Lekarz weterynarii – specjalista chorób drobiu i ptaków ozdobnych',
'Lekarz weterynarii – specjalista chorób koni',
'Lekarz weterynarii – specjalista chorób owadów użytkowych',
'Lekarz weterynarii – specjalista chorób przeżuwaczy',
'Lekarz weterynarii – specjalista chorób psów i kotów',
'Lekarz weterynarii – specjalista chorób ryb',
'Lekarz weterynarii – specjalista chorób trzody chlewnej',
'Lekarz weterynarii – specjalista chorób zwierząt futerkowych',
'Lekarz weterynarii – specjalista chorób zwierząt nieudomowionych',
'Lekarz weterynarii – specjalista epizootiologii i administracji weterynaryjnej',
'Lekarz weterynarii – specjalista higieny zwierząt rzeźnych i żywności pochodzenia zwierzęcego',
'Lekarz weterynarii – specjalista prewencji weterynaryjnej i higieny pasz',
'Lekarz weterynarii – specjalista radiologii weterynaryjnej',
'Lekarz weterynarii – specjalista rozrodu zwierząt',
'Lekarz weterynarii – specjalista użytkowania i patologii zwierząt laboratoryjnych',
'Lekarz weterynarii – specjalista weterynaryjnej diagnostyki laboratoryjnej',
'Lektor dialogów filmowych i radiowych',
'Lektor języka obcego',
'Licytator',
'Liczarz',
'Lider klubu pracy',
'Likwidator szkód',
'Listonosz',
'Lobbysta',
'Logopeda',
'Ludwisarz',
'Lustrzarz',
'Lutowacz',
'Ładowacz',
'Ładowacz nieczystości płynnych',
'Ładowacz nieczystości stałych',
'Łazienkowa',
'Łubiankarz',
'Magazynier',
'Maglarz',
'Makler giełd towarowych',
'Makler morski',
'Makler nadzorujący',
'Makler papierów wartościowych',
'Malarz-tapeciarz',
'Malarz budowlany',
'Malarz-lakiernik samolotowy',
'Malarz-lakiernik konstrukcji i wyrobów metalowych',
'Manewrowy',
'Manewrowy metra',
'Manikiurzystka',
'Manipulant drewna okrągłego',
'Marynarz motorzysta żeglugi śródlądowej',
'Marynarz statku morskiego',
'Marynarz żeglugi śródlądowej',
'Masztalerz',
'Maszynista',
'Maszynista agregatów prądotwórczych',
'Maszynista chłodni',
'Maszynista doku',
'Maszynista górniczych maszyn wyciągowych',
'Maszynista kolei linowych, wyciągów narciarskich i zjeżdżalni grawitacyjnych',
'Maszynista kotła',
'Maszynista maszyn fleksograficznych',
'Maszynista maszyn offsetowych',
'Maszynista maszyn typograficznych',
'Maszynista maszyn wklęsłodrukowych',
'Maszynista obsługujący urządzenia do napełniania i opróżniania zbiorników',
'Maszynista pociągu metra',
'Maszynista pomocniczych pojazdów kolejowych metra',
'Maszynista specjalistycznych dźwignic kolejowych',
'Maszynista sprężarek',
'Maszynista turbozespołu parowego',
'Maszynista turbozespołu wodnego',
'Maszynista urządzeń ciepłowniczych elektrowni',
'Maszynista urządzeń nawęglania',
'Maszynista urządzeń odpopielania i odżużlania',
'Maszynista urządzeń pomocniczych elektrowni',
'Maszynista wentylatorów w kopalni',
'Maszynistka',
'Maszynowy szlifierz-polerowacz szkła',
'Maślarz',
'Matematyk',
'Mechanik-monter maszyn i urządzeńS',
'Mechanik / konserwator urządzeń do napełniania i opróżniania zbiorników',
'Mechanik / konserwator urządzeń dźwignicowych',
'Mechanik autobusów',
'Mechanik automatyki przemysłowej i urządzeń precyzyjnychS',
'Mechanik ciągników',
'Mechanik lotniczy obsługi technicznej',
'Mechanik maszyn i urządzeń budowlanych i melioracyjnych',
'Mechanik maszyn i urządzeń do obróbki metali',
'Mechanik maszyn i urządzeń drogowychS',
'Mechanik maszyn i urządzeń górnictwa odkrywkowego',
'Mechanik maszyn i urządzeń górnictwa podziemnego',
'Mechanik maszyn i urządzeń przemysłowych',
'Mechanik maszyn rolniczych',
'Mechanik maszyn szwalniczych',
'Mechanik motocyklowyS',
'Mechanik okrętowy',
'Mechanik płatowców',
'Mechanik pojazdów samochodowychS',
'Mechanik pokładowy',
'Mechanik precyzyjnyS',
'Mechanik samochodów ciężarowych',
'Mechanik samochodów osobowych',
'Mechanik silników lotniczych',
'Mechanik silników spalinowych',
'Mechanik statkowy żeglugi śródlądowej',
'Mechanik taboru kolejowego',
'Mechanik urządzeń chłodniczych',
'Mechanik urządzeń klimatyzacyjnych',
'Mechanik wyposażenia lotniczego statków powietrznych',
'Mechanik-operator pojazdów i maszyn rolniczychS',
'Mediator',
'Mediator sądowy',
'Meliorant',
'Menedżer artystyczny',
'Menedżer dyscypliny sportu',
'Menedżer imprez sportowych',
'Menedżer klubu muzycznego',
'Menedżer marki (brand manager)',
'Menedżer produktu.(product manager)',
'Menedżer sportu',
'Menedżer zawartości serwisów internetowych',
'Metaloplastyk',
'Meteorolog',
'Metodyk edukacji na odległość',
'Metodyk technologii informacyjnych i komunikacyjnych',
'Metrolog',
'Mikrobiolog',
'Mikser dźwięku',
'Mikser obrazu',
'Mim',
'Mistrz produkcji w budownictwie drogowym',
'Mistrz produkcji w budownictwie kolejowym',
'Mistrz produkcji w budownictwie mostowym',
'Mistrz produkcji w budownictwie ogólnym',
'Mistrz produkcji w budownictwie przemysłowym',
'Mistrz produkcji w budownictwie wodnym',
'Mistrz produkcji w poligrafii',
'Mistrz produkcji w przemyśle chemicznym',
'Mistrz produkcji w przemyśle drzewnym',
'Mistrz produkcji w przemyśle elektromaszynowym',
'Mistrz produkcji w przemyśle elektronicznym',
'Mistrz produkcji w przemyśle farmaceutycznym',
'Mistrz produkcji w przemyśle metalurgicznym',
'Mistrz produkcji w przemyśle samochodowym',
'Mistrz produkcji w przemyśle spożywczym',
'Mistrz produkcji w przemyśle włókienniczym',
'Młynarz',
'Modelarz odlewniczyS',
'Modelarz odlewnik gipsowych form roboczych',
'Modelarz wyrobów plecionkarskich',
'Modelka / model',
'Modystka',
'Moletownik',
'Montażysta dekoracji',
'Montażysta dźwięku',
'Montażysta obrazu',
'Montażysta reprodukcyjny',
'Monter-instalator urządzeń technicznych w budownictwie wiejskim',
'Monter / konserwator kolei linowych, wyciągów narciarskich i zjeżdżalni grawitacyjnych',
'Monter / konserwator urządzeń przeciwpożarowych',
'Monter / konserwator urządzeń zabezpieczeń technicznych osób i mienia',
'Monter / konserwator instalacji wentylacyjnych i klimatyzacyjnych',
'Monter / składacz okien',
'Monter aparatów i przyrządów optycznych',
'Monter aparatury i urządzeń chemicznych',
'Monter aparatury i urządzeń techniki jądrowej',
'Monter aparatury rozdzielczej i kontrolnej energii elektrycznej',
'Monter bram',
'Monter budownictwa wodnegoS',
'Monter elektronicznego wyposażenia maszyn i urządzeń',
'Monter-elektronik – aparatura medyczna',
'Monter-elektronik – aparatura pomiarowa',
'Monter-elektronik – elektroniczne instrumenty muzyczne',
'Monter-elektronik – elektroniczny sprzęt sygnalizacyjny i systemy sygnalizacyjne',
'Monter-elektronik – instalacja anten',
'Monter-elektronik – naprawa sprzętu audiowizualnego',
'Monter-elektronik – sprzęt komputerowy',
'Monter-elektronik – układy elektroniczne automatyki przemysłowej',
'Monter-elektronik – urządzenia radiokomunikacyjne',
'Monter-elektronik – urządzenia radiowo-telewizyjne',
'Monter elektroniki samochodowej',
'Monter elektrycznego sprzętu gospodarstwa domowego',
'Monter elektrycznych przyrządów pomiarowych',
'Monter fasad',
'Monter fortepianów i pianin',
'Monter instalacji gazowych',
'Monter instalacji gazów medycznych',
'Monter instalacji i urządzeń sanitarnych',
'Monter instalacji i urządzeń telekomunikacyjnych (telemonter)',
'Monter instrumentów muzycznych',
'Monter izolacji budowlanychS',
'Monter izolacji chemoodpornych i antykorozyjnych',
'Monter izolacji przemysłowychS',
'Monter kadłubów okrętowychS',
'Monter kamiennych elementów budowlanych',
'Monter konstrukcji aluminiowych',
'Monter konstrukcji budowlanychS',
'Monter konstrukcji linowych stałych',
'Monter konstrukcji stalowych',
'Monter kotłów i armatury kotłowej',
'Monter maszyn elektrycznych',
'Monter maszyn i urządzeń okrętowych',
'Monter maszyn i urządzeń przemysłowych',
'Monter mebli',
'Monter mechanizmów i przyrządów precyzyjnych',
'Monter mechatronikS',
'Monter nawierzchni kolejowejS',
'Monter obrabiarek',
'Monter ociepleń budynków',
'Monter osprzętu elektrotechnicznego',
'Monter płatowców i śmigłowców',
'Monter płyt kartonowo-gipsowych',
'Monter podzespołów i zespołów elektronicznych',
'Monter pojazdów i urządzeń transportowych',
'Monter reklam',
'Monter rurociągów górniczych',
'Monter rurociągów okrętowych',
'Monter rurociągów przemysłowych',
'Monter rusztowań',
'Monter samochodowej instalacji gazowej (LPG)',
'Monter sieci cieplnych',
'Monter sieci deszczownianych',
'Monter sieci gazowych',
'Monter sieci i urządzeń telekomunikacyjnychS',
'Monter sieci telekomunikacyjnych',
'Monter sieci wodnych i kanalizacyjnych',
'Monter sieci, instalacji i urządzeń sanitarnychS',
'Monter silników spalinowych',
'Monter sprzętu gospodarstwa domowego',
'Monter sprzętu oświetleniowego i lamp elektrycznych',
'Monter sprzętu radiowego i telewizyjnego',
'Monter stolarki budowlanej',
'Monter systemów rurociągowychS',
'Monter systemów suchej zabudowy',
'Monter szkła budowlanego',
'Monter taboru szynowego',
'Monter układów hydraulicznych i pneumatycznych',
'Monter urządzeń chłodniczych i gastronomicznych',
'Monter urządzeń energetyki odnawialnej',
'Monter urządzeń laserowych',
'Monter urządzeń sterowania ruchem kolejowym',
'Monter urządzeń sterowania ruchem pociągów metra',
'Monter urządzeń zdalnego sterowania i kontroli dyspozytorskiej metra',
'Monter wiązek elektrycznych',
'Monter wiertni',
'Monter wyrobów tekstylnych, z tektury i pokrewnych materiałów',
'Monter wyrobów z drewna',
'Monter wyrobów z tworzyw sztucznych',
'Monter zabudowy i robót wykończeniowych w budownictwieS',
'Monter zestrajacz urządzeń elektronicznych',
'Monter znaków nawigacyjnych',
'Monter żaluzji',
'Monter-elektronikS',
'Monter-mechanik rowerów / wózków',
'Mostowniczy',
'Motorzysta wachtowy',
'Murarz',
'Murarz-tynkarzS',
'Muzealnik',
'MuzykS',
'Muzykolog',
'Muzykoterapeuta',
'Mygłowacz',
'Naczelnik / kierownik wydziału',
'Nanotechnolog (inżynier nanostruktur)',
'Napełniający zbiorniki przenośne',
'Nastawniczy',
'Naturopata',
'Nauczyciel specjalista terapii pedagogicznej',
'Nauczyciel / instruktor praktycznej nauki zawodu',
'Nauczyciel akademicki – nauki biologiczne',
'Nauczyciel akademicki – nauki chemiczne',
'Nauczyciel akademicki – nauki ekonomiczne',
'Nauczyciel akademicki – nauki farmaceutyczne',
'Nauczyciel akademicki – nauki fizyczne',
'Nauczyciel akademicki – nauki humanistyczne',
'Nauczyciel akademicki – nauki leśne',
'Nauczyciel akademicki – nauki matematyczne',
'Nauczyciel akademicki – nauki medyczne',
'Nauczyciel akademicki – nauki o kulturze fizycznej',
'Nauczyciel akademicki – nauki o Ziemi',
'Nauczyciel akademicki – nauki prawne',
'Nauczyciel akademicki – nauki rolnicze',
'Nauczyciel akademicki – nauki techniczne',
'Nauczyciel akademicki – nauki teologiczne',
'Nauczyciel akademicki – nauki weterynaryjne',
'Nauczyciel akademicki – nauki wojskowe',
'Nauczyciel akademicki – sztuki filmowe',
'Nauczyciel akademicki – sztuki muzyczne',
'Nauczyciel akademicki – sztuki plastyczne',
'Nauczyciel akademicki – sztuki teatralne',
'Nauczyciel bibliotekarz',
'Nauczyciel biologii',
'Nauczyciel chemii',
'Nauczyciel domowy',
'Nauczyciel doradca metodyczny',
'Nauczyciel etyki',
'Nauczyciel etyki w szkole podstawowej',
'Nauczyciel fizyki i astronomii',
'Nauczyciel geografii',
'Nauczyciel historii',
'Nauczyciel historii i społeczeństwa w szkole podstawowej',
'Nauczyciel informatyki / technologii informacyjnej',
'Nauczyciel informatyki w szkole podstawowej',
'Nauczyciel instruktor',
'Nauczyciel języka obcego',
'Nauczyciel języka obcego w szkole podstawowej',
'Nauczyciel języka polskiego',
'Nauczyciel języka polskiego w szkole podstawowej',
'Nauczyciel konsultant',
'Nauczyciel logopeda',
'Nauczyciel matematyki',
'Nauczyciel matematyki w szkole podstawowej',
'Nauczyciel muzyki',
'Nauczyciel muzyki w placówkach pozaszkolnych',
'Nauczyciel muzyki w szkole podstawowej',
'Nauczyciel nauczania na odległość',
'Nauczyciel nauczania początkowego',
'Nauczyciel niedostosowanych społecznie (pedagog resocjalizacji socjoterapeuta)',
'Nauczyciel niesłyszących i słabosłyszących (surdopedagog)',
'Nauczyciel niewidomych i słabowidzących (tyflopedagog)',
'Nauczyciel plastyki',
'Nauczyciel plastyki w szkole podstawowej',
'Nauczyciel przedmiotów zawodowych artystycznych',
'Nauczyciel przedmiotów zawodowych ekonomicznych',
'Nauczyciel przedmiotów zawodowych medycznych',
'Nauczyciel przedmiotów zawodowych rolniczych i leśnych',
'Nauczyciel przedmiotów zawodowych technicznych',
'Nauczyciel przedmiotów zawodowych turystycznych',
'Nauczyciel przedsiębiorczości',
'Nauczyciel przedszkola',
'Nauczyciel przewlekle chorych i niepełnosprawnych ruchowo',
'Nauczyciel przyrody w szkole podstawowej',
'Nauczyciel przysposobienia obronnego',
'Nauczyciel psycholog',
'Nauczyciel religii',
'Nauczyciel religii w szkole podstawowej',
'Nauczyciel sztuki w placówkach pozaszkolnych',
'Nauczyciel techniki',
'Nauczyciel techniki w szkole podstawowej',
'Nauczyciel technologii informatycznych w placówkach pozaszkolnych',
'Nauczyciel upośledzonych umysłowo (oligofrenopedagog)',
'Nauczyciel w placówkach pozaszkolnych',
'Nauczyciel wiedzy o kulturze',
'Nauczyciel wiedzy o społeczeństwie',
'Nauczyciel wychowania do życia w rodzinie',
'Nauczyciel wychowania fizycznego',
'Nauczyciel wychowania fizycznego w szkole podstawowej',
'Nawigator lotniczy',
'Negocjator biznesowy',
'Negocjator policyjny',
'Neurologopeda',
'Normalizator',
'Noszowy',
'Notariusz',
'Nurek',
'Obchodowy bloku',
'Obserwator radarowy żeglugi śródlądowej',
'Obuwnik miarowy',
'Obuwnik ortopedyczny',
'Obuwnik przemysłowy',
'ObuwnikS',
'Oceanolog',
'Oczyszczacz kanalizacyjny (kanalarz)',
'Oczyszczacz konstrukcji stalowych',
'Odczytywacz liczników',
'Odlewnik wyrobów ceramicznych',
'Odlewnik wyrobów z materiałów polimerowych',
'Odprawiacz pociągów',
'Oficer automatyk okrętowy',
'Oficer mechanik',
'Oficer pokładowy',
'Oficer portu',
'Oficer sił zbrojnych',
'Ogrodnik – uprawa grzybów jadalnych',
'Ogrodnik – uprawa roślin ozdobnych',
'Ogrodnik – uprawa warzyw polowych',
'Ogrodnik – uprawy pod osłonami',
'Ogrodnik producent nasion',
'OgrodnikS',
'Ogrodnik szkółkarz',
'Ogrodnik terenów zieleni',
'Operator-mechanik wyciągarki szybowcowej',
'Operator (maszynista) stacji pomp',
'Operator agregatów do obróbki cieplnej',
'Operator agregatów natryskowych',
'Operator aparatury utylizacji odpadów toksycznych',
'Operator aplikacji komputerowych',
'Operator automatów ceglarskich i wapienno - piaskarskich',
'Operator automatów do formowania wyrobów szklanych',
'Operator automatycznej linii obróbki skrawaniem',
'Operator badań defektoskopowych',
'Operator bezprzewodowych sieci komputerowych',
'Operator CAD',
'Operator centrali telefonicznej',
'Operator ciągników zrywkowych do zrywki podwieszanej',
'Operator DTP',
'Operator dźwięku',
'Operator dźwignic linotorowych',
'Operator edytorów tekstu',
'Operator fotoskładu',
'Operator kalandrów wyrobów papierowych',
'Operator kamery',
'Operator komputerowych urządzeń peryferyjnych',
'Operator kontroli bezpieczeństwa',
'Operator koparki',
'Operator koparko-ładowarki',
'Operator kserokopiarek',
'Operator linii do belowania makulatury',
'Operator ładowarki',
'Operator maszyn czyszczących',
'Operator maszyn do formowania szkła płaskiego',
'Operator maszyn do lakierowania i laminowania przetworów papierowych',
'Operator maszyn do obróbki skrawaniem',
'Operator maszyn do produkcji drutów i prętów',
'Operator maszyn do produkcji opakowań z papieru i tektury',
'Operator maszyn do produkcji papierowych artykułów piśmiennych',
'Operator maszyn do produkcji papierowych artykułów toaletowych i sanitarnych',
'Operator maszyn do produkcji papieru i tektury falistej',
'Operator maszyn do produkcji papy',
'Operator maszyn do produkcji płyt i sklejek',
'Operator maszyn do produkcji sznurka i tulei',
'Operator maszyn do produkcji taśm magnetycznych',
'Operator maszyn do produkcji włóknin i przędzin',
'Operator maszyn do produkcji wyrobów drewnianych',
'Operator maszyn do produkcji wyrobów z drutu, lin, siatek i kabli',
'Operator maszyn do przygotowania włókien',
'Operator maszyn drogowych',
'Operator maszyn dziewiarskich',
'Operator maszyn i sprzętu torowego',
'Operator maszyn i urządzeń chemicznej obróbki skór',
'Operator maszyn i urządzeń do obróbki plastycznejS',
'Operator maszyn i urządzeń do pozyskiwania torfu',
'Operator maszyn i urządzeń do produkcji łożysk tocznych',
'Operator maszyn i urządzeń do produkcji okien z tworzyw sztucznych',
'Operator maszyn i urządzeń do produkcji opakowań blaszanych',
'Operator maszyn i urządzeń do przerobu torfu',
'Operator maszyn i urządzeń do przeróbki mechanicznej rud',
'Operator maszyn i urządzeń do przeróbki mechanicznej węgla',
'Operator maszyn i urządzeń do przetwórstwa tworzyw sztucznychS',
'Operator maszyn i urządzeń do rozdrabniania i sortowania surowców mineralnych',
'Operator maszyn i urządzeń mechanicznej obróbki skór',
'Operator maszyn i urządzeń metalurgicznychS',
'Operator maszyn i urządzeń odlewniczychS',
'Operator maszyn i urządzeń przemysłu spożywczegoS',
'Operator maszyn i urządzeń wikliniarskich',
'Operator maszyn introligatorskich',
'Operator maszyn kopertujących',
'Operator maszyn krojących i wykrawających do papieru',
'Operator maszyn leśnychS',
'Operator maszyn ogrodniczych',
'Operator maszyn przędzalniczych',
'Operator maszyn przygotowawczych do wytwarzania płaskich wyrobów włókienniczych',
'Operator maszyn rolniczych',
'Operator maszyn tapicerskich',
'Operator maszyn tkackich',
'Operator maszyn urabiających i ładujących',
'Operator maszyn w przemyśle włókienniczymS',
'Operator maszyn wykończalniczych wyrobów włókienniczych',
'Operator maszyn zapałczanych',
'Operator maszyny odwadniającej celulozę',
'Operator maszyny papierniczej',
'Operator maszyny rozlewniczej',
'Operator maszyny tekturniczej',
'Operator minilabu fotograficznego',
'Operator mostu zwodzonego',
'Operator myjni',
'Operator nasiębiernych ciągników zrywkowych',
'Operator obrabiarek skrawającychS',
'Operator obrabiarek sterowanych numerycznie',
'Operator obrabiarek zespołowych',
'Operator obrazu',
'Operator obuwniczych urządzeń szwalniczych',
'Operator odprężarek wyrobów szklanych',
'Operator pergaminiarki',
'Operator pieców do obróbki cieplnej',
'Operator pilarek do pozyskiwania tarcicy',
'Operator pociągowy',
'Operator pras do formowania wyrobów z masy papierniczej',
'Operator pras kuźniczych',
'Operator pras w produkcji drzewnej',
'Operator przenośników',
'Operator przenośników taśmowych',
'Operator przewijarek i skręcarek nitek',
'Operator radiowych urządzeń transmisyjnych',
'Operator reaktora',
'Operator reaktorów i autoklawów',
'Operator robotów i manipulatorów przemysłowych',
'Operator robotów spawalniczych',
'Operator sieci komputerowych',
'Operator skanera poligraficznego',
'Operator sklejarek płyt stolarskich',
'Operator skrawarek drewna',
'Operator spajarek okleiny i łuszczki',
'Operator spalarni odpadów komunalnych',
'Operator sprzętu ciężkiego',
'Operator sprzętu komputerowego',
'Operator sprzętu zdjęciowego (wózkarz)',
'Operator spycharki',
'Operator strugarek i frezarek do drewna',
'Operator suwnic (suwnicowy)',
'Operator systemów komputerowych',
'Operator systemów nurkowych',
'Operator systemów sterylizacji artykułów sanitarnych, sprzętu i aparatów medycznych',
'Operator śluzy, jazu, zapory i pompowni',
'Operator tankowania statków powietrznych',
'Operator telewizyjnych urządzeń transmisyjnych',
'Operator urządzeń bielących masy włókniste',
'Operator urządzeń destylacyjnych',
'Operator urządzeń do chemicznego polerowania szkła',
'Operator urządzeń do ciągłego odlewania stali',
'Operator urządzeń do cięcia folii i płyt',
'Operator urządzeń do ekstrakcji',
'Operator urządzeń do elektroforetycznego nakładania powłok',
'Operator urządzeń do elektrolitycznego uzyskiwania metali',
'Operator urządzeń do emaliowania',
'Operator urządzeń do formowania bloków i tynków gipsowych',
'Operator urządzeń do formowania i przetwórstwa włókna szklanego',
'Operator urządzeń do formowania wyrobów ceramicznych',
'Operator urządzeń do formowania wyrobów ogniotrwałych',
'Operator urządzeń do formowania wyrobów sylikatowych',
'Operator urządzeń do formowania wyrobów z tworzyw sztucznych',
'Operator urządzeń do gięcia szkła',
'Operator urządzeń do hartowania szkła',
'Operator urządzeń do impregnowania i powlekania wyrobów papierowych',
'Operator urządzeń do klejenia elementów odzieży',
'Operator urządzeń do konfekcjonowania herbaty',
'Operator urządzeń do końcowej obróbki płyt',
'Operator urządzeń do krystalizacji',
'Operator urządzeń do matowania wyrobów szklanych',
'Operator urządzeń do mielenia masy włóknistej',
'Operator urządzeń do mycia, napełniania i zamykania butelek',
'Operator urządzeń do nakładania powłok galwanicznych',
'Operator urządzeń do natryskowego nakładania powłok',
'Operator urządzeń do obróbki błon i filmów fotograficznych',
'Operator urządzeń do obróbki cieplnej chemikaliów',
'Operator urządzeń do obróbki odwiertów wydobywczych',
'Operator urządzeń do obróbki płomieniowej szkła',
'Operator urządzeń do obróbki surowca mleczarskiego',
'Operator urządzeń do paletyzacji',
'Operator urządzeń do platerowania',
'Operator urządzeń do polerowania drewna',
'Operator urządzeń do prania, prasowania i chemicznego czyszczenia tekstyliów',
'Operator urządzeń do produkcji cementu',
'Operator urządzeń do produkcji chemikaliów nieorganicznych',
'Operator urządzeń do produkcji chemikaliów organicznych',
'Operator urządzeń do produkcji cukru',
'Operator urządzeń do produkcji dezynfektantów',
'Operator urządzeń do produkcji elementów z betonu komórkowego',
'Operator urządzeń do produkcji gazów technicznych',
'Operator urządzeń do produkcji katalizatorów',
'Operator urządzeń do produkcji koncentratów spożywczych',
'Operator urządzeń do produkcji majonezu i musztardy',
'Operator urządzeń do produkcji makaronu',
'Operator urządzeń do produkcji mas asfaltobetonowych',
'Operator urządzeń do produkcji mas bitumicznych',
'Operator urządzeń do produkcji materiałów półprzewodnikowych',
'Operator urządzeń do produkcji materiałów ściernych',
'Operator urządzeń do produkcji materiałów wybuchowych i pokrewnych',
'Operator urządzeń do produkcji napojów bezalkoholowych',
'Operator urządzeń do produkcji nawozów sztucznych',
'Operator urządzeń do produkcji ołówków',
'Operator urządzeń do produkcji pasz',
'Operator urządzeń do produkcji pieczywa',
'Operator urządzeń do produkcji piwa',
'Operator urządzeń do produkcji sadzy',
'Operator urządzeń do produkcji spirytusu',
'Operator urządzeń do produkcji sztucznej skóry',
'Operator urządzeń do produkcji środków piorących i myjących',
'Operator urządzeń do produkcji termosów',
'Operator urządzeń do produkcji tłuszczów roślinnych',
'Operator urządzeń do produkcji węgli aktywnych',
'Operator urządzeń do produkcji wina',
'Operator urządzeń do produkcji włókien chemicznych',
'Operator urządzeń do produkcji wyrobów cukierniczych',
'Operator urządzeń do produkcji wyrobów farmaceutycznych',
'Operator urządzeń do produkcji wyrobów kosmetycznych',
'Operator urządzeń do produkcji wyrobów mleczarskich',
'Operator urządzeń do produkcji wyrobów spirytusowych',
'Operator urządzeń do przerobu ziarna kakaowego',
'Operator urządzeń do przerobu ziarna zbóż',
'Operator urządzeń do przeróbki ropy naftowej i gazu',
'Operator urządzeń do przetwórstwa drobiu',
'Operator urządzeń do przetwórstwa kawy',
'Operator urządzeń do przetwórstwa mięsa',
'Operator urządzeń do przetwórstwa owocowo-warzywnego',
'Operator urządzeń do przetwórstwa ryb',
'Operator urządzeń do przetwórstwa surowców gumowych',
'Operator urządzeń do przetwórstwa ziemniaczanego',
'Operator urządzeń do przygotowania powierzchni do nakładania powłok',
'Operator urządzeń do przygotowywania i dozowania dodatków masowych',
'Operator urządzeń do spieniania tworzyw sztucznych',
'Operator urządzeń do suszenia zbóż',
'Operator urządzeń do ścierania drewna',
'Operator urządzeń do wulkanizacji',
'Operator urządzeń do wyważania i centrowania',
'Operator urządzeń do zanurzeniowego nakładania powłok',
'Operator urządzeń elewatorów zbożowych',
'Operator urządzeń filtrujących',
'Operator urządzeń granulujących',
'Operator urządzeń homogenizujących',
'Operator urządzeń kaletniczych',
'Operator urządzeń klimatyzacyjnych i odpylających',
'Operator urządzeń koksowniczych',
'Operator urządzeń linii aseptycznego rozlewu w opakowania kartonowe',
'Operator urządzeń ładunkowych silosu',
'Operator urządzeń mieszających',
'Operator urządzeń montażowych obuwia',
'Operator urządzeń nadawczych telewizji kablowej',
'Operator urządzeń oczyszczania ścieków',
'Operator urządzeń pakujących',
'Operator urządzeń próżniowego odgazowania stali',
'Operator urządzeń przemysłu ceramicznegoS',
'Operator urządzeń przemysłu chemicznegoS',
'Operator urządzeń przemysłu szklarskiegoS',
'Operator urządzeń przemysłu tytoniowego',
'Operator urządzeń przygotowania wsadu',
'Operator urządzeń radiokomunikacyjnych',
'Operator urządzeń rębalni drewna',
'Operator urządzeń rozdrabniających',
'Operator urządzeń rozwłókniających',
'Operator urządzeń sorpcyjnych',
'Operator urządzeń technicznych stosowanych w leśnictwie',
'Operator urządzeń utylizacji surowców zwierzęcych',
'Operator urządzeń uzdatniania i demineralizacji wody',
'Operator urządzeń walcowni',
'Operator urządzeń warzelni',
'Operator urządzeń wykrawających elementy obuwia',
'Operator urządzeń wykrawających i nawarstwiających',
'Operator urządzeń wyparnych',
'Operator urządzeń wytwórczych mieszanek betonowych',
'Operator urządzeń znakujących',
'Operator wielooperacyjnych samojezdnych maszyn leśnych',
'Operator wieżowy przenośnika taśmowego',
'Operator wirówek',
'Operator wprowadzania danych',
'Operator wtryskarki',
'Operator wywrotnic wagonowych',
'Operator zautomatyzowanej linii produkcyjnej',
'Operator zgrzewarek',
'Operator zintegrowanych systemów zarządzania zasobami firmy',
'Operator zrywkowych kolejek linowych',
'Operator żurawia jezdniowego',
'Operator żurawia wieżowego',
'Opiekun dzieci na przejściach dla pieszych',
'Opiekun dzikich zwierząt',
'Opiekun klienta',
'Opiekun medycznyS',
'Opiekun osoby starszejS',
'Opiekun w domu pomocy społecznejS',
'Opiekun zwierząt domowych',
'Opiekunka domowa',
'Opiekunka dzieci w drodze do szkoły',
'Opiekunka dziecięca domowa (niania)',
'Opiekunka dziecięcaS',
'Opiekunka środowiskowaS',
'Opiekunka w żłobku / klubie dziecięcym',
'Optoelektronik',
'Optometrysta',
'Optyk-mechanikS',
'Optyk okularowy',
'Organista',
'Organizator imprez rozrywkowych (organizator eventów)',
'Organizator imprez sportowych',
'Organizator imprez ślubnych',
'Organizator obsługi sprzedaży internetowej',
'Organizator transportu drogowego',
'Organizator usług domowych',
'Organizator usług kateringowych',
'Organizator usług konferencyjnych',
'Organizator usług pogrzebowych',
'Organizator widowni',
'Organomistrz',
'Ortopeda mechanik',
'OrtoptystkaS',
'Osoba do towarzystwa',
'Osoby dozoru ruchu w górnictwie odkrywkowym',
'Osoby dozoru ruchu w górnictwie otworowym',
'Osoby dozoru ruchu w górnictwie podziemnym',
'Osoba wykwalifikowana w przemyśle farmaceutycznym',
'Osobisty doradca do spraw zakupów (personal shopper)',
'Osteopata',
'Oświetlacz filmowy',
'Pakowacz ręczny',
'Palacz gazowych kotłów centralnego ogrzewania',
'Palacz kotłów parowych',
'Palacz pieców zwykłych',
'Palacz wodnych rusztowych kotłów centralnego ogrzewania',
'Palowniczy',
'Pamiątkarz',
'Parasolnik',
'Parkieciarz',
'Parkingowy',
'Parlamentarzysta',
'Parzelniczy drewna',
'Patroszacz ryb',
'Pedagog',
'Pedagog animacji kulturalnej',
'Pedagog mediów',
'Pedagog specjalny',
'Pedagog szkolny',
'Pedikiurzystka',
'Perfumiarz',
'Perfuzjonista',
'Perukarz',
'Piaskarz',
'Piecowy nagrzewania wsadu w walcowni',
'Piecowy pieca łukowego',
'PiekarzS',
'Pielęgniarka',
'Pielęgniarka oddziałowa',
'Pielęgniarka – specjalista organizacji i zarządzania',
'Pielęgniarka – specjalista pielęgniarstwa anestezjologicznego i intensywnej opieki',
'Pielęgniarka – specjalista pielęgniarstwa chirurgicznego',
'Pielęgniarka – specjalista pielęgniarstwa diabetologicznego',
'Pielęgniarka – specjalista pielęgniarstwa epidemiologicznego',
'Pielęgniarka – specjalista pielęgniarstwa geriatrycznego',
'Pielęgniarka – specjalista pielęgniarstwa kardiologicznego',
'Pielęgniarka – specjalista pielęgniarstwa nefrologicznego',
'Pielęgniarka – specjalista pielęgniarstwa neonatologicznego',
'Pielęgniarka – specjalista pielęgniarstwa neurologicznego',
'Pielęgniarka – specjalista pielęgniarstwa onkologicznego',
'Pielęgniarka – specjalista pielęgniarstwa operacyjnego',
'Pielęgniarka – specjalista pielęgniarstwa opieki długoterminowej',
'Pielęgniarka – specjalista pielęgniarstwa opieki paliatywnej',
'Pielęgniarka – specjalista pielęgniarstwa pediatrycznego',
'Pielęgniarka – specjalista pielęgniarstwa psychiatrycznego',
'Pielęgniarka – specjalista pielęgniarstwa ratunkowego',
'Pielęgniarka – specjalista pielęgniarstwa rodzinnego',
'Pielęgniarka – specjalista pielęgniarstwa środowiska nauczania i wychowania',
'Pielęgniarka – specjalista pielęgniarstwa w ochronie zdrowia pracujących',
'Pielęgniarka – specjalista pielęgniarstwa zachowawczego',
'Pielęgniarka – specjalista promocji zdrowia i edukacji zdrowotnej',
'Pielęgniarz trawników /murawy (greenkeeper)',
'Pilarz',
'Pilarz kamienia',
'Pilot balonu wolnego',
'Pilot morski',
'Pilot pionowzlotu',
'Pilot samolotowy zawodowy / liniowy',
'Pilot sterowcowy zawodowy',
'Pilot szybowcowy',
'Pilot śmigłowcowy zawodowy / liniowy',
'Pilot wiatrakowcowy zawodowy',
'Pilot wycieczek',
'Pilot żeglugi śródlądowej',
'Piosenkarz',
'Pirotechnik',
'Pisarz',
'Planista produkcyjny',
'PlastykS',
'Plecionkarz',
'Płatnerz',
'Płetwonurek ratownik',
'Poborca skarbowy',
'Podkuwacz koni',
'Podoficer sił zbrojnych',
'Podolog',
'Poeta',
'Pokojowa',
'Polerowacz wyrobów z drewna',
'Policjant służy kryminalnej',
'Policjant służy prewencyjnej',
'Policjant służy wspomagającej',
'Politolog',
'Polityk (minister, sekretarz / podsekretarz stanu)',
'Położna',
'Położna oddziałowa',
'Położna – specjalista organizacji i zarządzania',
'Położna – specjalista pielęgniarstwa epidemiologicznego',
'Położna – specjalista pielęgniarstwa ginekologicznego',
'Położna – specjalista pielęgniarstwa neonatologicznego',
'Położna – specjalista pielęgniarstwa położniczego',
'Położna – specjalista pielęgniarstwa rodzinnego',
'Położna – specjalista promocji zdrowia i edukacji zdrowotnej',
'Pomoc apteczna',
'Pomoc dentystyczna',
'Pomoc domowa',
'Pomoc krawiecka',
'Pomoc kuchenna',
'Pomoc laboratoryjna',
'Pomocniczy robotnik budowlany',
'Pomocniczy robotnik drogowy',
'Pomocniczy robotnik konserwacji terenów zieleni',
'Pomocniczy robotnik leśny',
'Pomocniczy robotnik mostowy',
'Pomocniczy robotnik polowy',
'Pomocniczy robotnik przy uprawie roślin i hodowli zwierząt',
'Pomocniczy robotnik szklarniowy',
'Pomocniczy robotnik torowy',
'Pomocniczy robotnik w gospodarstwie rybackim',
'Pomocniczy robotnik w gospodarstwie sadowniczym',
'Pomocniczy robotnik w hodowli zwierząt',
'Pomocniczy robotnik w łowiectwie',
'Pomocniczy robotnik w przemyśle przetwórczym',
'Pomocnik biblioteczny',
'Pomocnik ciastkarza',
'Pomocnik lakiernika',
'Pomocnik mechanika',
'Pomocnik mleczarski',
'Pomocnik piekarza',
'Portier',
'Posadzkarz',
'Pośrednik finansowy',
'Pośrednik pracy',
'Pośrednik usług medycznych',
'Pośrednik w obrocie nieruchomościami',
'Pozłotnik',
'Pracownik agencji pracy tymczasowej',
'Pracownik biura podróży',
'Pracownik biura przepustek',
'Pracownik centrum elektronicznej obsługi klienta',
'Pracownik centrum obsługi telefonicznej (pracownik call center)',
'Pracownik deratyzacji, dezynfekcji i dezynsekcji',
'Pracownik do spraw ewidencji ludności',
'Pracownik do spraw kredytów',
'Pracownik do spraw kultury fizycznej i sportu',
'Pracownik do spraw osobowych',
'Pracownik do spraw pożyczek',
'Pracownik do spraw produktów finansowych',
'Pracownik do spraw socjalnych',
'Pracownik do spraw statystyki',
'Pracownik do spraw ubezpieczeń',
'Pracownik do spraw ubezpieczeń medycznych',
'Pracownik działu logistyki',
'Pracownik galerii / muzeum',
'Pracownik informacji turystycznej',
'Pracownik instytucji pożyczkowej',
'Pracownik kancelaryjny',
'Pracownik kolektury',
'Pracownik lombardu',
'Pracownik obsługi bankomatów',
'Pracownik obsługi kampanii e-mailowych',
'Pracownik obsługi monitoringu',
'Pracownik obsługi klienta instytucji finansowej',
'Pracownik obsługi płacowej',
'Pracownik ochrony fizycznej',
'Pracownik ochrony roślin',
'Pracownik oczyszczania terenu z materiałów wybuchowych i niebezpiecznych',
'Pracownik parafialny',
'Pracownik pomocniczy obsługi hotelowejS',
'Pracownik pozycjonowania stron internetowych',
'Pracownik prac dorywczych',
'Pracownik pralni chemicznej',
'Pracownik przeprowadzkowy',
'Pracownik przygotowujący posiłki typu fast food',
'Pracownik punktu skupu',
'Pracownik rozkładający towar na półkach',
'Pracownik scentralizowanych systemów rozliczeniowych',
'Pracownik socjalny',
'Pracownik solarium',
'Pracownik sortowania przesyłek i towarów',
'Pracownik w biurze maklerskim',
'Pracownik wylęgarni drobiu',
'Pracownik wynajmu powierzchni komercyjnych',
'Pracownik zarządzania kryzysowego',
'Pracownik zbiórki odpadów',
'Praczka',
'Prasowacz ceramiki elektronicznej i elektrotechnicznej',
'Prasowaczka ręczna',
'Preparator medyczny',
'Prezenter muzyczny (DJ / didżej)',
'Prezenter telewizyjny',
'Prezes',
'Probierz',
'Producent filmowy',
'Producent i zbieracz ziół',
'Producent teatralny',
'Producent telewizyjny',
'Producent żywności ekologicznej',
'Programista aplikacji',
'Programista aplikacji mobilnych',
'Projektant / architekt systemów teleinformatycznych',
'Projektant aplikacji multimedialnych, animacji i gier komputerowych',
'Projektant baz danych',
'Projektant biżuterii',
'Projektant ekspozycji towarów i usług (visual merchandiser)',
'Projektant grafiki',
'Projektant grafiki stron internetowych',
'Projektant mody',
'Projektant pakietów usług finansowych',
'Projektant stron internetowych (webmaster)',
'Projektant systemów alarmowych',
'Projektant wzornictwa przemysłowego',
'Prokurator',
'Promotor marki (trendsetter)',
'Protetyk słuchuS',
'Prowadzący maszyny do kolejowych robót budowlanych',
'Prowadzący rodzinny dom dziecka',
'Przedstawiciel handlowy',
'Przedstawiciel medyczny',
'Przedstawiciel władzy samorządowej (marszałek, starosta, radny)',
'Przetwórca owoców i warzyw',
'Przetwórca ryb',
'Przewodnik turystyczny górski',
'Przewodnik turystyczny miejski',
'Przewodnik turystyczny terenowy',
'Przewoźnik osób',
'Przewoźnik żeglugi śródlądowej',
'Przędzarz',
'Przygotowywacz mas ceramicznych',
'Przygotowywacz włókna',
'Psycholog',
'Psycholog biznesu',
'Psycholog kliniczny',
'Psycholog organizacji',
'Psycholog sportowy',
'Psycholog wychowawczy',
'Psychoonkolog',
'Psychoterapeuta',
'Psychotraumatolog',
'PszczelarzS',
'Pulpitowy wielkich pieców',
'Radca prawny',
'Radca Prokuratorii Generalnej Skarbu Państwa',
'Radiesteta',
'Ratownik górniczy',
'Ratownik górski',
'Ratownik medyczny',
'Ratownik morski',
'Ratownik pokładowy',
'Ratownik wodny',
'Realizator dźwięku',
'Realizator filmu wideo (wideofilmowiec)',
'Realizator programu telewizyjnego / radiowego',
'Realizator rekonstrukcji dźwięku',
'Realizator światła',
'Recepcjonista',
'Recepcjonista hotelowy',
'Redaktor programowy',
'Redaktor serwisu internetowego',
'Redaktor wydawniczy',
'Referendarz sądowy',
'Refleksolog',
'Regionalny kierownik sprzedaży',
'Rejestratorka medyczna',
'Rektor',
'Rekwizytor',
'Religioznawca',
'Renowator mebli artystycznych',
'Renowator tkanin unikatowych',
'Renowator zabytków architektury',
'Reporter radiowy / telewizyjny / prasowy',
'Reżyser dźwięku',
'Rewident kontroli skarbowej',
'Rewident taboru',
'Rewizor pociągów',
'Rezydent biura turystycznego',
'Reżyser filmowy',
'Reżyser teatralny',
'Reżyser telewizyjny / radiowy',
'Ręczny polerowacz szkła',
'Ręczny znakowacz wyrobów',
'Rękawicznik',
'Rękodzielnik wyrobów skórzanych',
'Rękodzielnik wyrobów włókienniczychS',
'Robotnik gospodarczy',
'Robotnik górniczy dołowy',
'Robotnik leśny',
'Robotnik magazynowy',
'Robotnik myjący części i zespoły',
'Robotnik naziemny w górnictwie',
'Robotnik oczyszczania miasta',
'Robotnik osuszania i odgrzybiania budowli',
'Robotnik placowy',
'Robotnik pracujący na rampie',
'Robotnik portowy (doker)',
'Robotnik rozbiórki budowli',
'Rodzic zastępczy',
'Rolnik chmielarz',
'Rolnik łąkarz',
'Rolnik producent kwalifikowanych nasion rolniczych',
'Rolnik produkcji roślinnej i zwierzęcej pracujący na własne potrzeby',
'Rolnik produkcji roślinnej pracujący na własne potrzeby',
'RolnikS',
'Rolnik upraw mieszanych',
'Rolnik upraw polowych',
'Rozbieracz–wykrawacz',
'Rozlepiacz afiszy',
'Rusznikarz',
'Rybak pracujący na własne potrzeby',
'Rybak rybołówstwa morskiego',
'Rybak śródlądowyS',
'Rykszarz',
'Rymarz',
'Rysownik geodezyjny',
'Rysownik kartograficzny',
'Rysownik litograficzny',
'Rytownik',
'Rzecznik patentowy',
'Rzeczoznawca',
'Rzeczoznawca budowlany',
'Rzeczoznawca do spraw bezpieczeństwa i higieny pracy',
'Rzeczoznawca jakości handlowej artykułów rolno-spożywczych',
'Rzeczoznawca majątkowy',
'Rzeczoznawca rolniczy',
'Rzeczoznawca samochodowy',
'Rzeźbiarz w drewnie',
'Rzeźbiarz szkła',
'Rzeźbiarz w owocach i warzywach',
'Rzeźnik-wędliniarz',
'Sadownik',
'Salowa',
'Sanitariusz szpitalny',
'Scenarzysta',
'Scenograf',
'Sekretarka',
'Sekretarka medyczna',
'Sekretarka notarialna',
'Sekretarka w kancelarii prawnej',
'Sekretarz konsularny',
'Sekretarz planu filmowego',
'Sekretarz sądowy',
'Serowar',
'Serwisant sprzętu komputerowego',
'Serwisant urządzeń medycznych',
'Sędzia',
'Sędzia sportowy',
'Siostra PCK',
'Sitarz',
'Skarbnik bankowy',
'Składacz sprzętu spadochronowego',
'Skoczek spadochronowy',
'Socjolog',
'Sommelier',
'Sortowacz',
'Sortowacz-brakarz ceramiki',
'Sortowacz-brakarz szkła',
'Sortowacz odpadów komunalnych',
'Sortowacz materiałów drzewnych',
'Sortowacz surowców wtórnych',
'Spawacz',
'Specjalista administracji publicznej',
'Specjalista analizy i rozwoju rynku',
'Specjalista bankowości',
'Specjalista bezpieczeństwa i higieny pracy',
'Specjalista bezpieczeństwa oprogramowania',
'Specjalista bezpieczeństwa systemów teleinformatycznych',
'Specjalista etyki biznesu',
'Specjalista fizjoterapii',
'Specjalista do spraw adopcji',
'Specjalista do spraw animacji multimedialnej',
'Specjalista do spraw audytu zabezpieczenia',
'Specjalista do spraw badań społeczno-ekonomicznych',
'Specjalista do spraw controllingu',
'Specjalista do spraw czasowego zatrudniania pracowników',
'Specjalista do spraw dietetyki',
'Specjalista do spraw doskonalenia i rozwoju aplikacji',
'Specjalista do spraw doskonalenia organizacji',
'Specjalista do spraw ergonomii i projektowania form użytkowych',
'Specjalista do spraw factoringu',
'Specjalista do spraw integracji europejskiej',
'Specjalista do spraw kadr',
'Specjalista do spraw kluczowych klientów (key account manager)',
'Specjalista do spraw konsultingu',
'Specjalista do spraw komercjalizacji innowacyjnych technologii',
'Specjalista do spraw kultury firmy',
'Specjalista do spraw logistyki',
'Specjalista do spraw marketingu i handlu',
'Specjalista do spraw mediów interaktywnych',
'Specjalista do spraw obsługi posprzedażowej',
'Specjalista do spraw ochrony własności intelektualnej',
'Specjalista do spraw organizacji i rozwoju przemysłu',
'Specjalista do spraw organizacji i rozwoju sprzedaży',
'Specjalista do spraw organizacji i rozwoju transportu',
'Specjalista do spraw organizacji usług gastronomicznych, hotelarskich i turystycznych',
'Specjalista do spraw pakowania i opakowań',
'Specjalista do spraw planowania strategicznego',
'Specjalista do spraw pozyskiwania funduszy (fundraiser)',
'Specjalista do spraw public relations',
'Specjalista do spraw rachunkowości',
'Specjalista do spraw rachunkowości inwestycyjnej',
'Specjalista do spraw rachunkowości podatkowej',
'Specjalista do spraw rachunkowości zarządczej',
'Specjalista do spraw reklamy',
'Specjalista do spraw rekrutacji pracowników',
'Specjalista do spraw rozwoju oprogramowania systemów informatycznych',
'Specjalista do spraw rozwoju stron internetowych',
'Specjalista do spraw rozwoju zawodowego',
'Specjalista do spraw sprzedaży',
'Specjalista do spraw stosunków międzynarodowych',
'Specjalista do spraw szkoleń',
'Specjalista do spraw tworzenia biznes planów',
'Specjalista do spraw ubezpieczeń majątkowych i osobowych',
'Specjalista do spraw ubezpieczeń społecznych',
'Specjalista do spraw ubezpieczeń zdrowotnych',
'Specjalista do spraw uzależnień od mediów cyfrowych',
'Specjalista do spraw wynagrodzeń',
'Specjalista do spraw zamówień publicznych',
'Specjalista do spraw zarządzania talentami',
'Specjalista do spraw zarządzania w oświacie',
'Specjalista informacji naukowej, technicznej i ekonomicznej',
'Specjalista inżynierii medycznej',
'Specjalista komunikacji społecznej',
'Specjalista kontroli jakości',
'Specjalista marketingu społecznego',
'Specjalista monitoringu systemów zabezpieczeń technicznych osób i mienia',
'Specjalista ochrony informacji niejawnych',
'Specjalista ochrony środowiska',
'Specjalista organizacji i zarządzania w ochronie zdrowia',
'Specjalista polityki społecznej',
'Specjalista poradnictwa psychospołecznego i rodzinnego',
'Specjalista pracy socjalnej',
'Specjalista promocji zdrowia i edukacji zdrowotnej',
'Specjalista psychoterapii uzależnień',
'Specjalista do spraw ratownictwa medycznego',
'Specjalista radiofarmacji',
'Specjalista resocjalizacji',
'Specjalista sprzedaży internetowej',
'Specjalista sprzedaży technologii i usług informatycznych',
'Specjalista systemów rozpoznawania mowy',
'Specjalista terapii uzależnień',
'Specjalista integracji międzykulturowej',
'Specjalista zaopatrzenia medycznego',
'Specjalista zarządzania informacją',
'Specjalista zarządzania kryzysowego',
'Specjalista zarządzania ryzykiem (underwriter)',
'Specjalista zastosowań informatyki',
'Specjalista zdrowia publicznego',
'Specjalista zdrowia środowiskowego',
'Specjalista żywienia człowieka',
'Spedytor',
'Spiker radiowy',
'Sprzątacz pojazdów',
'Sprzątaczka biurowa',
'Sprzątaczka domowa',
'Sprzedawca na targowisku / bazarze',
'Sprzedawca na telefon',
'Sprzedawca obwoźny z samochodu (vanseller)',
'Sprzedawca reklam internetowych',
'SprzedawcaS',
'Sprzedawca w branży mięsnej',
'Sprzedawca w branży przemysłowej',
'Sprzedawca w branży spożywczej',
'Sprzedawca w stacji paliw',
'Statysta',
'Statystyk',
'Stenograf-protokolant',
'Stermotorzysta żeglugi śródlądowej',
'Sternik żeglugi śródlądowej',
'Sterowniczy linii sztaplowania i pakietowania tarcicy',
'Steward statku morskiego',
'Stewardesa / Steward',
'Stokażowy',
'Stolarz budowlany',
'Stolarz galanterii drzewnej',
'Stolarz mebli artystycznych i wzorcowych',
'Stolarz meblowy',
'Stolarz modelarz instrumentów muzycznych',
'StolarzS',
'Strażak',
'Strażnik gminny / miejski',
'Strażnik leśny',
'Strażnik łowiecki',
'Strażnik ochrony przyrody / środowiska',
'Strażnik rybacki',
'Strażnik straży marszałkowskiej',
'Strażnik w zakładzie dla nieletnich',
'Stroiciel fortepianów i pianinS',
'Strugacz',
'Strugacz drewna',
'Strzałowy (górnik strzałowy)',
'Studniarz',
'Sufler',
'Surdologopeda',
'Suszarnik ceramiki i wyrobów gipsowych',
'Suszarniowy drewna',
'Sygnalista szybowy',
'Syndyk',
'Synoptyk',
'Szaleciarz',
'Szatniarz',
'Szczotkarz',
'Szef kuchni (kuchmistrz)',
'Szewc',
'Szklarz',
'Szklarz budowlany',
'Szklarz pojazdów',
'Szkliwierz ceramiki',
'Szkutnik',
'Szlifierz ceramiki',
'Szlifierz kamieni szlachetnych i ozdobnych',
'Szlifierz kamienia',
'Szlifierz materiałów drzewnych',
'Szlifierz metali',
'Szlifierz-ostrzarz',
'Szlifierz-polerowacz szkła optycznego',
'Szlifierz-polerowacz wyrobów artystycznych',
'Szlifierz szkła gospodarczego i technicznego',
'Szlifierz szkła płaskiego',
'Szpachlarz',
'Sztauer-trymer',
'Sztukator',
'Szwaczka maszynowa',
'Szwaczka ręczna',
'Szyldziarz',
'Szyper',
'Ślusarz galanterii metalowej',
'Ślusarz narzędziowy',
'ŚlusarzS',
'Świecki krzewiciel wiary',
'Tajemniczy klient (mystery shopper)',
'Takielarz',
'Taksator',
'Taksator ryzyka działalności firm',
'Taksówkarz',
'Tanatoprakser (balsamista)',
'Tancerz baletowy',
'TancerzS',
'Tapeciarz',
'Tapicer meblowy',
'TapicerS',
'Tartacznik',
'Tatuażysta',
'Technik administracjiS',
'Technik agrobiznesuS',
'Technik akustyk',
'Technik analitykS',
'Technik analityki medycznej',
'Technik analizy i monitoringu środowiska',
'Technik architekt',
'Technik architektury krajobrazuS',
'Technik archiwistaS',
'Technik automatyk',
'Technik automatyk sterowania ruchem kolejowymS',
'Technik awionikS',
'Technik bezpieczeństwa i higieny pracyS',
'Technik budownictwa okrętowegoS',
'Technik budownictwaS',
'Technik budownictwa wodnegoS',
'Technik budowy fortepianów i pianinS',
'Technik cyfrowych procesów graficznychS',
'Technik dentystycznyS',
'Technik dozymetrysta',
'Technik drogownictwaS',
'Technik dróg i mostów kolejowychS',
'Technik dźwięku',
'Technik ekonomistaS',
'Technik eksploatacji portów i terminaliS',
'Technik elektroenergetyk transportu szynowegoS',
'Technik elektronikS',
'Technik elektroniki i informatyki medycznejS',
'Technik elektroniki medycznej',
'Technik elektroradiologS',
'Technik elektryk kolejowych sieci elektroenergetycznych',
'Technik elektrykS',
'Technik elektryk samochodowy',
'Technik elektryk urządzeń zabezpieczenia i sterowania ruchem kolejowym',
'Technik energetykS',
'Technik farmaceutycznyS',
'Technik fizjoterapii',
'Technik garbarzS',
'Technik gazownictwaS',
'Technik geodetaS',
'Technik geofizyk',
'Technik geologS',
'Technik gospodarki odpadami',
'Technik górnictwa odkrywkowegoS',
'Technik górnictwa otworowegoS',
'Technik górnictwa podziemnegoS',
'Technik handlowiecS',
'Technik hodowca koniS',
'Technik hodowca zwierząt',
'Technik hotelarstwaS',
'Technik hutnikS',
'Technik hydrolog',
'Technik informacji naukowej',
'Technik informatykS',
'Technik instrumentów muzycznych',
'Technik inżynierii środowiska i melioracjiS',
'Technik kryminalistyki',
'Technik konserwator urządzeń dźwigowych',
'Technik księgarstwaS',
'Technik leśnikS',
'Technik logistykS',
'Technik lotniskowych służb operacyjnych',
'Technik masażystaS',
'Technik mechanik budowy środków transportu',
'Technik mechanik eksploatacji środków transportu',
'Technik mechanik lotniczyS',
'Technik mechanik maszyn i urządzeń',
'Technik mechanik obróbki skrawaniem',
'Technik mechanik okrętowyS',
'Technik mechanik precyzyjny',
'Technik mechanikS',
'Technik mechanik urządzeń przemysłowych',
'Technik mechanizacji rolnictwaS',
'Technik mechatronikS',
'Technik meteorolog',
'Technik metrolog',
'Technik nawigator morskiS',
'Technik normowania pracy',
'Technik obsługi turystycznejS',
'Technik obuwnikS',
'Technik ochrony fizycznej osób i mieniaS',
'Technik ochrony środowiskaS',
'Technik odlewnikS',
'Technik ogrodnikS',
'Technik optykS',
'Technik organizacji produkcji',
'Technik organizacji reklamyS',
'Technik ortopedaS',
'Technik papiernictwaS',
'Technik pojazdów samochodowychS',
'Technik poligraf',
'Technik pożarnictwaS',
'Technik prac biurowychS',
'Technik procesów drukowaniaS',
'Technik procesów introligatorskichS',
'Technik przeróbki kopalin stałychS',
'Technik przetwórstwa mleczarskiegoS',
'Technik przetwórstwa tworzyw sztucznych',
'Technik pszczelarzS',
'Technik rachunkowościS',
'Technik realizacji dźwiękuS',
'Technik realizacji nagrań i nagłośnieńS',
'Technik renowacji elementów architekturyS',
'Technik rolnikS',
'Technik rybactwa śródlądowegoS',
'Technik rybołówstwa morskiegoS',
'Technik spedytorS',
'Technik sterylizacji medycznejS',
'Technik systemów zabezpieczeń technicznych osób i mienia',
'Technik sztukatorstwa i kamieniarstwa artystycznego',
'Technik technologii ceramicznejS',
'Technik technologii chemicznejS',
'Technik technologii drewnaS',
'Technik technologii materiałów budowlanych',
'Technik technologii odzieżyS',
'Technik technologii szkłaS',
'Technik technologii środków farmaceutycznych',
'Technik technologii środków kosmetycznych',
'Technik technologii wyrobów skórzanychS',
'Technik technologii żywności – cukrownictwo',
'Technik technologii żywności – produkcja cukiernicza',
'Technik technologii żywności – produkcja koncentratów spożywczych',
'Technik technologii żywności – produkcja piekarsko-ciastkarska',
'Technik technologii żywności – przechowalnictwo chłodnicze i technologia żywności mrożonej',
'Technik technologii żywności – przetwórstwo fermentacyjne',
'Technik technologii żywności – przetwórstwo jajczarsko-drobiarskie',
'Technik technologii żywności – przetwórstwo mięsne',
'Technik technologii żywności – przetwórstwo mleczarskie',
'Technik technologii żywności – przetwórstwo owocowo-warzywne',
'Technik technologii żywności – przetwórstwo rybne',
'Technik technologii żywności – przetwórstwo surowców olejarskich',
'Technik technologii żywności – przetwórstwo zbożowe',
'Technik technologii żywności – przetwórstwo ziemniaczane',
'Technik technologii żywnościS',
'Technik teleinformatykS',
'Technik telekomunikacjiS',
'Technik transportu drogowegoS',
'Technik transportu kolejowegoS',
'Technik turystyki wiejskiejS',
'Technik tyfloinformatykS',
'Technik urządzeń audiowizualnych',
'Technik chłodnictwa i klimatyzacjiS',
'Technik urządzeń dźwigowychS',
'Technik urządzeń i systemów energetyki odnawialnejS',
'Technik urządzeń ruchu lotniczego',
'Technik urządzeń sanitarnychS',
'Technik usług fryzjerskichS',
'Technik usług kosmetycznychS',
'Technik usług pocztowych i finansowychS',
'Technik utrzymania ruchu',
'Technik weterynariiS',
'Technik wiertnikS',
'Technik włókienniczych wyrobów dekoracyjnychS',
'Technik włókiennikS',
'Technik zabezpieczeń przeciwkorozyjnych',
'Technik żeglugi śródlądowejS',
'Technik żywienia i gospodarstwa domowego',
'Technik żywienia i usług gastronomicznychS',
'Technolog inżynierii telekomunikacyjnej',
'Technolog robót wykończeniowych w budownictwie',
'Technolog – programista obrabiarek',
'Teleankieter',
'Telemarketer',
'Teolog',
'Terapeuta środowiskowy',
'Terapeuta zajęciowyS',
'Termoizoler',
'Tester oprogramowania komputerowego',
'Tester systemów teleinformatycznych',
'Tkacz',
'Tłoczarz w metalu',
'Tłumacz',
'Tłumacz języka migowego',
'Tokarz / frezer obrabiarek sterowanych numerycznie',
'Tokarz w drewnie',
'Tokarz w metalu',
'Toksykolog',
'Topiarz fryty',
'Topiarz mas mineralnych',
'Topiarz szkła',
'Toromistrz',
'Towaroznawca',
'Tragarz',
'Traser',
'Trawiacz poligraficzny',
'Trener koni wyścigowych',
'Trener osobisty (coach, mentor, tutor)',
'Trener sportu',
'Treser psów',
'Treser zwierząt cyrkowych',
'Trzciniarz',
'Twórca ludowy',
'Tynkarz',
'Ubojowy',
'Układacz-konserwator spadochronów',
'Układacz nawierzchni drogowych',
'Uliczny sprzedawca produktów nieżywnościowych / żywności o długim terminie przydatności do spożycia',
'Uliczny sprzedawca żywności o krótkim terminie przydatności do spożycia',
'Uliczny zmywacz szyb samochodowych',
'Urbanista',
'Urzędnik do spraw imigracji',
'Urzędnik do spraw licencji',
'Urzędnik do spraw paszportów',
'Urzędnik do spraw udzielania pozwoleń na budowę',
'Urzędnik do spraw udzielania pozwoleń na prowadzenie działalności gospodarczej',
'Urzędnik podatkowy',
'Urzędnik ubezpieczeń społecznych',
'Ustawiacz',
'Ustawiacz maszyn do obróbki drewna',
'Ustawiacz maszyn do obróbki skrawaniem',
'Wagowy',
'Weterynaryjny kontroler sanitarny',
'WędliniarzS',
'Wiertacz w drewnie',
'WiertaczS',
'Wiertacz studni',
'Wiertacz w metalu',
'Windykator',
'Witrażownik',
'Wizażystka / stylistka',
'Wizytator',
'Właściciel małego sklepu',
'Właściciel małego zakładu agroturystycznego / hotelarskiego / gastronomicznego',
'Wokalista',
'Wozak',
'Wozak zrywkarz',
'Woźny',
'Wróżbita',
'Wulkanizator',
'Wulkanizator taśm przenośnikowych',
'Wybieracz monet / żetonów z automatów',
'Wychowawca małego dziecka',
'Wychowawca w jednostkach penitencjarnych',
'Wychowawca w placówkach oświatowych, wsparcia dziennego, wychowawczych i opiekuńczych oraz',
'cjonalnej pieczy zastępczej',
'Wydawca materiałów',
'Wydawca środków strzałowych',
'Wydawca posiłków / bufetowy',
'Wydobywca kruszywa i gliny',
'Wykładowca na kursach (edukator, trener)',
'Wypalacz surowców i wyrobów ogniotrwałych',
'Wypalacz wyrobów ceramicznych',
'Wyprawiacz skór futerkowych',
'Wytapiacz metali nieżelaznych',
'Wytapiacz stali, surówki i żelazostopów',
'Wytwórca abażurów',
'Wytwórca galanterii',
'Wytwórca sztucznych kwiatów',
'Wyższy urzędnik państwowy',
'Wyższy urzędnik placówki dyplomatycznej',
'Wyższy urzędnik samorządowy',
'Zabawkarz',
'Zabiegowy balneologiczny',
'Zakonnik (bez święceń kapłańskich)',
'Zalewacz form',
'Zamiatacz',
'Zaopatrzeniowiec',
'Zarządca energią',
'Zawiadowca stacji',
'Zawodnik dyscypliny sportu',
'Zawodowy działacz organizacji komercyjnej / pracodawców',
'Zawodowy działacz organizacji politycznej',
'Zawodowy działacz organizacji pozarządowej',
'Zawodowy działacz organizacji zawodowej',
'Zawodowy działacz organizacji związkowej',
'Zarządca nieruchomości',
'Zbieracz owoców, ziół i innych roślin',
'Zbrojarz',
'Zdobnik ceramiki',
'Zdobnik szkła',
'ZdunS',
'ZegarmistrzS',
'Zgrzewacz',
'Zielarz-fitoterapeuta',
'Złotnik-jubilerS',
'Zmywacz graffiti',
'Zmywacz naczyń',
'Zmywacz okien (czyściciel szyb)',
'Zoofizjoterapeuta',
'Zoopsycholog',
'Zwrotniczy',
'Żaglownik',
'Żałobnik',
'Żołnierz szeregowy',
'Żongler']


print(len(lista))

import random
random.shuffle(lista)
for a in range(0,20):
    print(a,"\t",lista[a])


